### ISSUE TITLE
Empfänger problem

### ISSUE THREAD

**Issue by Gatlingod** [iobroker-community-adapters/ioBroker.telegram#100]
Hi,

ich habe ein kleines Problem mit Empfängern. Obwohl ich restart meldungen bekomme und auch in einem Gruppenchat befehle nutzen kann. Schickt der Adapter mir persönlich keine msges mehr:

telegram.0 | 2019-04-16 18:57:01.747 | warn | 1 of 1 recipients are unknown!
-- | -- | -- | --
javascript.0 | 2019-04-16 18:57:01.743 | info | script.js.test: telegram['1x111xxxx']: lol

Das Problem hat entweder mit einem update begonnen, oder als ich einen zweiten Benutzer hinzugefügt hatte.

Inzwischen habe ich aber schon:
- verschiedene versionen getestet
- mit einem mit zwei benutzern (An alle geht übrigens... nur wenn ich explizit einen angebe ist das problem da)
- mit und ohne passwort.

bekomme ich irgendwie eine detailiertere debug Ausgabe?

**Comment by BuZZy1337** [comment]
Wie sieht denn der users Datenpunkt aus? Da sind alle Namen und id's der User aufgelistet.. 

Gruß

**Comment by Gatlingod** [comment]
das ist alles richtig, id, name alles gut wird eingetragen wie es soll.
{"1x111xxxx":"FxxBxxxx"}

**Comment by BuZZy1337** [comment]
Wenn du mit der ID des Users arbeitest, dann muss es chatId sein..
Also mit ID so:
```js
sendTo("telegram.0", "send", {
    text: 'lol',
    chatId: '1x111xxxx'
});
```
und wenn du den Username verwenden willst - dann so:
```js
sendTo("telegram.0", "send", {
    text: 'lol',
    user: 'FxxBxxxx'
});
```

Gruß

**Comment by Gatlingod** [comment]
ah.. ok thx. sry

Hat sich das geändert in irgend einem Update vor kurzem?

**Comment by BuZZy1337** [comment]
Nein das ist schon lange so.. Aber wenn du natürlich auf einer ganz alten Version warst und jetzt ein Update gemacht hast kann es natürlich sein dass da was geändert wurde.. :grin:
