### ISSUE TITLE
loud message on iOS even if the flag "disable_notification" is true. Same at blockly

### ISSUE THREAD

**Issue by unstressable** [iobroker-community-adapters/ioBroker.telegram#102]

**Comment by umbm** [comment]
Same effect at android for couple of months but occures not always.
Can't locate or reproduce the problem, sometimes the notification is muted, sometimes it's normal sound.

I contacted telegram support months ago an they tested the disable_notification without error.

**Comment by unstressable** [comment]
Hmm. For me the problem accurs always. Newest iOS and Telegram Version.
Maybe someone will find a problem.

**Comment by shady2k** [comment]
Same problem here. This property ignored.

**Comment by umbm** [comment]
Meanwhile the notification settings are ok on Android again. 
All messages sent with no-notification-flag from iobroker come in without notification in telegram on Android. 

Don't know what's going on... fixes in Telegram, the app or somewhere else..? 
For me it's working again this time.

**Comment by unstressable** [comment]
iOS works too actually. Don't know why, but everything is OK!
