### ISSUE TITLE
Fatal error in case of connection failure

### ISSUE THREAD

**Issue by fs-plugins** [iobroker-community-adapters/ioBroker.telegram#103]
please intercept the fatal error if the connection is terminated
(is unnecessary, e.g. forced separation by provider always triggers this)

"polling_error:EFATAL, EFATAL: Error: read ECONNRESET"

**Comment by BuZZy1337** [comment]
I dont really understand what you mean with "intercept" it?
What do you want the adapter to do if there is no internet connection and it gets an ECONNRESET?
Just suppress the error message?

**Comment by GermanBluefox** [comment]
Test the 1.5.6
