### ISSUE TITLE
offStatus in der Objekt-Konfiguration wird nicht übernommen

### ISSUE THREAD

**Issue by BramTown** [iobroker-community-adapters/ioBroker.telegram#107]
In den Objekt-Einstellungen kann eine telegram-Benachrichtigung aktiviert werden (Schraubenschlüssel-Symbol am Ende der Objektzeile).

Unter anderem gibt es hier die Möglichkeit die Meldungen für den "onStatus" und den "offStatus" zu setzen.

Während der Wert für den "onStatus" korrekt bei der Benachrichtigung übernommen wird, erhalte ich beim "offStatus" weiterhin den Standardwert "switched off" und nicht den hinterlegten, neuen Wert.

**Comment by beef76** [comment]
Hab das gleiche Problem, gibts hier schon nen Lösungsansatz?
