### ISSUE TITLE
HowTo: send mp3 ?

### ISSUE THREAD

**Issue by mmick08** [iobroker-community-adapters/ioBroker.telegram#111]
Hi Guys,

can you please provide an expample how to send mp3 files ?
When i try:

sendTo("telegram.0", "send", {
      text: "/tmp/my.mp3",
      user: <recipient>
  });

i am receiving the string instead of mp3 file :(

**Comment by cyptus** [comment]
you can specify a type additional to your path:

```
sendTo('telegram', {
	chatId: myChatId,
	text: '/path/to/file',
	type: 'audio' //photo, video, audio, document, sticker, action, location
});
```
