### ISSUE TITLE
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated

### ISSUE THREAD

**Issue by ThomasBahn** [iobroker-community-adapters/ioBroker.telegram#112]
found in my logs:

Caught | 2019-08-25 18:54:36.681 | error | by controller[0]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:778:30
-- | -- | -- | --
Caught | 2019-08-25 18:54:36.681 | error | by controller[0]: In the future, you will have to enable it yourself.
Caught | 2019-08-25 18:54:36.679 | error | by controller[0]: Sun, 25 Aug 2019 16:54:14 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.

**Comment by BuZZy1337** [comment]
Comment of a dependency which we dont have access to..
That message does not affect us.. 
But thanks for the report. :+1: :relaxed:
