### ISSUE TITLE
Adding an option to whitelist user based on TelegramID

### ISSUE THREAD

**Issue by mc-0815** [iobroker-community-adapters/ioBroker.telegram#113]
Hi,

I have a proposal to further increase security by adding an option to whitelist telegram userIDs that are allowed to send commands to the bot.

Adding users should be possible either by adding userIDs manually via the admin interface or by temporarily allow all users and using the already authenticated userIDs (kind of learning modus).

**Comment by BuZZy1337** [comment]
I don't understand your issue.. If you set a password in the instance settings only users who authenticated with that password are able to send commands to the adapter?

**Comment by mc-0815** [comment]
I think we all know that password auth is one of the weakest auth. So adding an option to restrict access by Telegram users via Telegram account Id will provide an additional layer of security. Depending on what you control by iobroker this might be worth to use. Hope this makes it a bit more clear.

**Comment by GermanBluefox** [comment]
https://github.com/iobroker-community-adapters/ioBroker.telegram#advanced-security 
Added in 1.9.0
