### ISSUE TITLE
problem with compact mode and JS-Controller 2.0.26

### ISSUE THREAD

**Issue by ihavenonick** [iobroker-community-adapters/ioBroker.telegram#116]
telegram.0 | 2019-10-13 17:04:27.787 | info | (25492) starting. Version 1.4.3 in /opt/iobroker/node_modules/iobroker.telegram, node: v10.16.3
-- | -- | -- | --
host.Beelink.compactgroup1 | 2019-10-13 17:04:25.057 | info | instance system.adapter.telegram.0 started with pid 25492
  | 2019-10-13 17:04:25.033 | error | ndefined
host.Beelink.compactgroup1 | 2019-10-13 17:04:25.033 | error | Cannot start telegram.0 in compact mode. Fallback to normal start! : require(...) is not a function
host.Beelink.compactgroup1 | 2019-10-13 17:04:25.027 | info | "system.adapter.telegram.0" enabled
host.Beelink | 2019-10-13 17:04:25.024 | info | instance system.adapter.telegram.0 is handled by compact group controller pid 16141
host.Beelink | 2019-10-13 17:04:25.023 | info | "system.adapter.telegram.0" enabled

**Comment by Apollon77** [comment]
Please try again with js-controller 2.0.40 and reopen if still problematic with updated log please. Thank you!
