### ISSUE TITLE
Verify Compact mode for your adapter

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.telegram#118]
We have detected that your adapter supports the compact mode. Please use the latest js-controller 2.0 and verify that everything works.

Some more information what is important to check can be found at https://github.com/ioBroker/ioBroker.js-controller/issues/512 

On questions please answer to the linked issue. Please close this issue after your test and add the version number that you have tested please as a comment.

Thank you for your support.

**Comment by cburghardt** [comment]
Compact mode is currently broken. I have enabled it but this morning I got:
 polling_error:ETELEGRAM, ETELEGRAM: 409 Conflict: terminated by other getUpdates request;

Unfortunately this is also not resolved by restarting the adapter. And when I disabled compact mode it kept repeating this error. I had to restart the js-controller to get rid of this spurious process.

**Comment by Apollon77** [comment]
Are you sure ut has something to do with the compact mode? The 409 happens when there are concurrent api accesses or such

**Comment by cburghardt** [comment]
At least I have never seen this before and don't have this issue anymore since I disabled compact mode. But I have no evidence ;)
