### ISSUE TITLE
Buttons using "answerCallbackQuery" cause the original message to be rewritten to "Ok"

### ISSUE THREAD

**Issue by systemofapwne** [iobroker-community-adapters/ioBroker.telegram#120]
When I press an inline button in my TG Bot menu, the whole message (some inline keyboard) completely rewrites that message to simply "Ok".

The root cause seems to be here:

https://github.com/iobroker-community-adapters/ioBroker.telegram/commit/08096118eb19f0f7af6e5c0d633b63604edfc849#r36388736

**Comment by GermanBluefox** [comment]
Should be fixed with 1.5.3
