### ISSUE TITLE
Telegram Adapter Bot postet nicht in Gruppe

### ISSUE THREAD

**Issue by digitalnaiveDE** [iobroker-community-adapters/ioBroker.telegram#121]
Hallo,

ich habe einen Bot den ich als Einzelperson bis dato problemlos benutzt habe. Allerdings würde ich gerne meine Frau ebenfalls über die Updates informieren.

Dafür habe ich mit meiner Frau eine Gruppe erstellt und den Bot dort hinzugefügt. Ebenfalls habe ich den Bot zum Admin gemacht und /setprivacy auf Disabled und /setjoingroups auf enabled gestellt.

In meinem "direkten" Chat mit dem Bot bekomme ich weiterhin die Push Nachricht, in die Gruppe liefert der Bot es aber trotzdem nicht. Was übersehe ich?

**Comment by BuZZy1337** [comment]
Du sagst dem Adapter aber auch dass er die Nachricht an den Gruppenchat senden soll?

**Comment by GermanBluefox** [comment]
NO answer from TS... Closed
