### ISSUE TITLE
Telegram bot ignores message

### ISSUE THREAD

**Issue by micudaj** [iobroker-community-adapters/ioBroker.telegram#122]
When sending a message to the bot it ignores the message claiming it is too old, but the times are accurate on sending  devices as well as the server.

Error message in log: Message from undefined ignored, becasue too old: (30300) <text>

**Comment by Dome2075** [comment]
Same problem!

**Comment by Dome2075** [comment]
someone know how to fix this problem?

Node.js = 10.18.0
JS controller = 2.2.7
Telegram adapter = 1.4.7

**Comment by micudaj** [comment]
I did a local workaround by removing the code that throws the error in the main.js inside node-modules

**Comment by Dome2075** [comment]
Can you show me what you have done?

**Comment by Dome2075** [comment]
I did it!

I detected that my internal-servertime was different.

Now it works!

**Comment by GermanBluefox** [comment]
Please activate ntp/sntp service on devices to have the same time as a telegram service.
