### ISSUE TITLE
Feature Request: Limit System Messages to specific users

### ISSUE THREAD

**Issue by ExecuteGK** [iobroker-community-adapters/ioBroker.telegram#127]
Adapter System messages, like Restarting... is sent to all registered users.
Please provide a checkbox, or any other configuration option, in order to specify which user shall receive those messages.

Thank you.
Sebastian

**Comment by cryptedx** [comment]
I was just about to post that too. I ask that this feature be included. Thank you.

**Comment by Soulguard** [comment]
Would be great, if you can add any configuration option for this. In my case, i don't need the recurring start/stop message every day. Maybe you can set a datapoint before the adapter stops or starts as an option.
Thank you and stay healthy!

**Comment by Apollon77** [comment]
>  i don't need the recurring start/stop message every day

Why you eve restart the adapter every day? ;-) it was kind of a default some time ago, I have it working without that since looong time

**Comment by Soulguard** [comment]
@Apollon77 I don't restart the adapter, the system does. ;) Maybe you can give me a hint, how to disable the dayly automatic restart early in the morning at 05:04 am.

**Comment by Apollon77** [comment]
Admin -> Expert mode -> Column "restart schedule" (or such)

**Comment by Soulguard** [comment]
Ahh...got it! Thank you @Apollon77

**Comment by GermanBluefox** [comment]
Should we assume, the issue is resolved?

**Comment by ExecuteGK** [comment]
I would lower the prio. It would be still nice to restrict system messages to certain users. SebastianVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Bluefox ***@***.***> Datum: 26.06.21  11:30  (GMT+01:00) An: "iobroker-community-adapters/ioBroker.telegram" ***@***.***> Cc: ExecuteGK ***@***.***>, Author ***@***.***> Betreff: Re: [iobroker-community-adapters/ioBroker.telegram] Feature Request:
  Limit System Messages to specific users (#127) 
Should we assume, the issue is resolved?

**Comment by GermanBluefox** [comment]
Implemented in 1.8.4
