### ISSUE TITLE
warnmeldung?!

### ISSUE THREAD

**Issue by toon2006** [iobroker-community-adapters/ioBroker.telegram#129]
adapter.getMessage is deprecated and will be removed in js-controller 2.3. Please report this warning to the developer of this adapter!

**Comment by Astromechdroide** [comment]
I have the same problem after updating the js controller

**Comment by BassT23** [comment]
for now, it's not a problem - it's an info ;)
Could it be fixed?

**Comment by Apollon77** [comment]
It already is fixed in latest version. Just not in stable repo
