### ISSUE TITLE
After last Update - user.split is not a function

### ISSUE THREAD

**Issue by 2scorpio** [iobroker-community-adapters/ioBroker.telegram#132]
Hello.
After upgrading to version 1.5.0, the menu stopped working.
In driver logs, telegraph is such an error:
2020-02-07 00:27:21.510  -  [33mwarn [39m: telegram.0 (10439) TypeError: user.split is not a function
at sendMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:641:32)
https://pastebin.com/b65xwA7Y

**Comment by 2scorpio** [comment]
Node.js = v8.15.0
JS controller = 2.2.8
Telegram adapter = 1.5.0

**Comment by GermanBluefox** [comment]
Wich message do you send?

**Comment by 2scorpio** [comment]
> Wich message do you send?

https://pastebin.com/f7C1QHiQ

**Comment by GermanBluefox** [comment]
> > Wich message do you send?
> 
> https://pastebin.com/f7C1QHiQ

Unfortunately I can't see which command is sent. I added in 1.5.2 debug information. Can you give me the logs with debug level?

**Comment by 2scorpio** [comment]
This is debug info
https://pastebin.com/dpbmJz3c

**Comment by Haba1234** [comment]
error due to incorrectly transmitted user.
The user is transferred to the adapter in json format 
`user = {"firstName":"user1","userName":"user1111"}`
but there must be an array or string:
`['user1','user2']` or `'user1'`
