### ISSUE TITLE
Version 1.5

### ISSUE THREAD

**Issue by AlexanderSch90** [iobroker-community-adapters/ioBroker.telegram#133]
Hallo zusammen, 
in version 1.5 wird immer nur ein Benutzer gespeichert. Sobald der zweite ich mit /password phrase anmeldet fliegt der erste wieder raus...

Bitte prüfen. Danke!

**Comment by MichaWilk** [comment]
Bestätige ich, bei mir auch.

**Comment by GermanBluefox** [comment]
Duplicate https://github.com/iobroker-community-adapters/ioBroker.telegram/issues/136
