### ISSUE TITLE
Ständige Passworteingabe

### ISSUE THREAD

**Issue by Tagiwara** [iobroker-community-adapters/ioBroker.telegram#136]
Ich benutze auf zwei Handys den gleichen Bot zur Steuerung unserer SmartHome Geräte mittels Blockly Script.

Seit kurzem ist es nur noch möglich, an einem Handy das Menü zu benutzen, an dem anderen Handy wird bei Benutzung nach dem Bot Passwort gefragt. Gebe ich es dort ein, kann ich an demanderen Handy den Telegram Bot nicht mehr benutzen und muss erst das Bot Passwort eingeben. Dadurch fliegt der andere wieder raus.

Im Adapter werden auch nicht mehr beide User unter "Gespeicherte Benutzer" angelegt, sondern nur noch der zuletzt mit Passwort eingeloggte User

**Comment by Tagiwara** [comment]
Node.js = v10.18.1
JS controller = 2.2.8
Telegram adapter = 1.5.0

**Comment by GermanBluefox** [comment]
Wie sehen die Settings in Konfig-Dialog aus?

**Comment by Pendora2017** [comment]
Den Fehler kann ich leider bestätigen. Nur noch der zuletzt authentifizierte Benutzer bleibt als User erhalten. Der andere fliegt sofort raus. 

NodeJS = 10.19.0
JS Controller = 2.2.7
Telegram Adapter = 1.5.0

Anbei die Screenshots von den Einstellungen
![Screenshot_2020-02-13 instances - ioBroker(1)](https://user-images.githubusercontent.com/28994273/74461084-3cc3aa00-4e8e-11ea-8d75-1a72795a4be1.jpg)
![Screenshot_2020-02-13 instances - ioBroker](https://user-images.githubusercontent.com/28994273/74461087-3df4d700-4e8e-11ea-8e21-c3e7c99a6650.jpg)

**Comment by Tagiwara** [comment]
Hallo zusammen, anbei meine Config vom Adapter

LG
Frank

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Donnerstag, 13. Februar 2020 18:26 schrieb Pendora <notifications@github.com>:

**Comment by Tagiwara** [comment]
![Telegram2](https://user-images.githubusercontent.com/41060053/74512487-ac767b00-4f08-11ea-86f9-4946e2d1800d.jpg)
![Telegram1](https://user-images.githubusercontent.com/41060053/74512491-aed8d500-4f08-11ea-9d1b-2588a5b2990a.jpg)

**Comment by aleb08** [comment]
Habe das gleiche Problem. Seit ich vor kurzem sowohl die Telegram App als auch den Adapter geupdatet habe. Sonst hätte man es eingrenzen können.
NodeJS = 10.19.0
JS Controller = 2.2.9
Telegram Adapter = 1.5.0

**Comment by Tagiwara** [comment]
Ist der Fehler in 1.5.1 behoben?

**Comment by aleb08** [comment]
Hab 1.4.7 drübergezogen und schon funktionierts wieder.

**Comment by Pendora2017** [comment]
Der Fehler existiert leider auch noch in der 1.5.1

**Comment by GermanBluefox** [comment]
Ich habe 1.5.2 und 1.5.1 ausprobiert und mit beiden kann ich von 2 Handys mit 2 unterschiedlichen Telegram Accounts kommunizieren. Kann jemand 1.5.2 ausprobieren?
Und waren das 2 unterschiedliche Telegram-Accounts oder gleiches Account und 2 Handys?

**Comment by Pendora2017** [comment]
Ich bin jetzt von 1.5.1 auf 1.5.3 gegangen und habe auch sonst alle Adapter geupdatet (socket.io, Admin usw usw.) aber das Problem bleibt bestehen.

Mein Aufbau: 
- eine Telegram Instanz
- 2 unterschiedliche Handy's mit jeweils 2 unterschiedlichen Telegram Accounts

**Comment by Tagiwara** [comment]
Ich bin von der 1.4.7 (wo alles läuft) auf die 1.5.3 gegangen. Problem besteht weiterhin. Sobald ich vom zweiten Handy schalten will, muss ich das Passwort eingebe und fliege bei Handy Nr. 1 raus.

Bin wieder zurück auf 1.4.7

Mein Aufbau ist auch

- eine Telegram Instanz
- 2 Iphone´s mit jeweils eigenem Telegram Acc
- Beide Accounts nutzen für as Menü den gleichen Bot

**Comment by Tagiwara** [comment]
Ich wäre zu einer Anydesk Sitzung bereit um dir das Problem einmal zu veranschaulichen

**Comment by Stan2449** [comment]
Hab das selbe 
Seit dem letzten Update akzeptiert der Adapter nur noch entweder mich oder meine Frau als Benutzer.
Wenn sich im Bot der eine mit /password anmeldet ersetzt er den anderen im Adapter gespeicherte Benutzer.

Wir haben unterschiedliche Namen und auch ID´s daran liergt es auch nicht.

Gab es eine Änderung im Adapter oder bei Telegram selbst ?

**Comment by drapone** [comment]
Kann das Problem leider auch bestätigen immer nur 1 aktiver User.

**Comment by AlexanderSch90** [comment]
Kann das Problem leider auch bestätigen immer nur 1 aktiver User. Habe alles upgedatet aus dem Latest...  Bin jetzt zurück auf 1.4.7 da geht es.

**Comment by Tingeltangelbobi** [comment]
Bei mir besteht das gleiche Problem mit Adapter Version 1.5.3

**Comment by Tagiwara** [comment]
Gerade mal getestet: Problem besteht auch mit der 1.5.4 weiterhin. Somit erneut downgrade auf 1.4.7

**Comment by BobBruni** [comment]
Gleiches Problem mit Version 1.5.4
js-controller: 2.2.9

Zwei Pixel3 Phones

**Comment by creativtransfer** [comment]
Seit der 1.5.5 scheint das Problem behoben zu sein.

**Comment by Pendora2017** [comment]
Auch bei mir scheint es mit der 1.5.5 wieder zu funktionieren.

Hatte vor einer Woche allerdings ein Downgrade auf 1.4.9 gemacht und bin von da jetzt auf 1.5.5 gesprungen. Wie es von 1.5.4 zu 1.5.5 ausschaut kann ich dadurch nicht sagen.
