### ISSUE TITLE
Telegram Adapter wird entfernt

### ISSUE THREAD

**Issue by ginvibe** [iobroker-community-adapters/ioBroker.telegram#137]
Mein Telegram Adapter schmeißt momentan folgende Warnung raus:

`telegram.0 | 2020-02-17 14:10:01.374 | warn | (9787) adapter.getMessage is deprecated and will be removed in js-controller 3.0. Please report this warning to the developer of this adapter!`

Wie kann ich das verhindern?

**Comment by Apollon77** [comment]
Nicht der Adapter wird entfernt :-) Nur eine Methode die der nutzt.

**Comment by Apollon77** [comment]
update comes soon to stable

**Comment by HGlab01** [comment]
@Apollon77: Warning still on stable version; maybe not updated yet?
