### ISSUE TITLE
adapter akzeptiert nur einen Benutzer bei anmeldung im bot

### ISSUE THREAD

**Issue by aleb08** [iobroker-community-adapters/ioBroker.telegram#138]
Seit dem letzten Update akzeptiert der Adapter nur noch entweder mich oder meine Frau als Benutzer.
Wenn sich im Bot der eine mit /password anmeldet ersetzt er den anderen im Adapter gespeicherte Benutzer.
Die letzten Jahre lief es einwandfei denn da waren beide als gespeicherte Benutzer eingetragen.
Wir haben unterschiedliche Namen und auch ID´s daran liergt es auch nicht.

Gab es eine Änderung im Adapter oder bei Telegram selbst ?

**Comment by aleb08** [comment]
same question like #136

**Comment by Michaelnorge** [comment]
Same here!
