### ISSUE TITLE
Telegram options on object level - missing documentation

### ISSUE THREAD

**Issue by RESDE** [iobroker-community-adapters/ioBroker.telegram#140]
Dear Developers,

I´m using the telegram adapter but handling the configuration of the option on each object level is neither documented nor run smoothly.
Issue 1: What means option write protected / schreibgeschützt ?
Issue 2: Triggers in line /Schaltflächen in Linie=
issue 3: only writing / nur schreiben?
issue 4: only true / nur wahr: Although this option activated the messenger sends switched off messages and flooding me with irrelevant infos.
I think these options should work as it is a comfortable configuration to trigger objetc state changes without manuell effords for scripting.
Please support and share solutions.
Best regards
Reiner

![grafik](https://user-images.githubusercontent.com/59728312/75433209-e35c8000-594f-11ea-9e4e-708d6cacac49.png)

**Comment by GermanBluefox** [comment]
https://github.com/iobroker-community-adapters/ioBroker.telegram#auto-inline-keyboard-based-on-settings-in-admin-easy-keyboard
