### ISSUE TITLE
Since reinstallation Telegram does not send any messages

### ISSUE THREAD

**Issue by Smarti15** [iobroker-community-adapters/ioBroker.telegram#142]
Hello

I have the following problem. My old Asus Tinkerboard is running Telegram. Now I have reinstalled a Raspberry Pi 4 and set up the Telegram adapter. It connects, the status in the adapter is green and the log shows no errors.  Unfortunately I don't get any messages on the phone anymore. If I start the Telegram Bot on the old computer, it immediately starts sending again. If I end the adapter on the old computer and start the adapter on the new computer, nothing arrives. I urgently need this great adapter, can you please help me?

I have tried it with version 1.5.3, but it does not work there either.
There is something about Redis in the log file. I have not installed Redis on the new server. Do I have to install it?

![2020-03-11 14_55_19-Window](https://user-images.githubusercontent.com/40327154/76424413-81b50080-63a8-11ea-9cf6-5ce3f204a39f.png)

![2020-03-11 14_54_50-Window](https://user-images.githubusercontent.com/40327154/76424417-824d9700-63a8-11ea-82c6-6eba9187fb75.png)

![2020-03-11 14_52_15-Window](https://user-images.githubusercontent.com/40327154/76424420-82e62d80-63a8-11ea-867b-6a5906896c10.png)

![2020-03-11 14_52_04-Window](https://user-images.githubusercontent.com/40327154/76424422-837ec400-63a8-11ea-8c7c-5040f7b45362.png)

![2020-03-11 14_51_42-Window](https://user-images.githubusercontent.com/40327154/76424423-84175a80-63a8-11ea-921f-bd92bb3ad0df.png)

![2020-03-11 14_51_26-Window](https://user-images.githubusercontent.com/40327154/76424424-84175a80-63a8-11ea-8708-c1faec1d9b85.png)

```
telegram.0 | 2020-03-11 14:50:11.129 | debug | (7381) system.adapter.admin.0: logging true
-- | -- | -- | --
telegram.0 | 2020-03-11 14:50:00.019 | debug | (7381) Received command "send": {"text":"Hallo"}
telegram.0 | 2020-03-11 14:49:42.604 | debug | (7381) system.adapter.admin.0: logging false
telegram.0 | 2020-03-11 14:49:00.006 | debug | (7381) Received command "send": {"text":"Hallo"}
telegram.0 | 2020-03-11 14:48:00.013 | debug | (7381) Received command "send": {"text":"Hallo"}
telegram.0 | 2020-03-11 14:47:00.021 | debug | (7381) Received command "send": {"text":"Hallo"}
telegram.0 | 2020-03-11 14:46:00.018 | debug | (7381) Received command "send": {"text":"Hallo"}
telegram.0 | 2020-03-11 14:45:31.647 | debug | (7381) getMe: {"id":106513xxxx,"is_bot":true,"first_name":"iobroker","username":"namebot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}
telegram.0 | 2020-03-11 14:45:31.456 | debug | (7381) Start polling with: 300(number) ms interval
telegram.0 | 2020-03-11 14:45:31.365 | debug | (7381) Schedule restart: 4 5 * * *
telegram.0 | 2020-03-11 14:45:31.279 | info | (7381) starting. Version 1.5.3 in /opt/iobroker/node_modules/iobroker.telegram, node: v10.19.0
telegram.0 | 2020-03-11 14:45:29.973 | debug | (7381) statesDB connected
telegram.0 | 2020-03-11 14:45:29.972 | debug | (7381) States connected to redis: 127.0.0.1:9000
telegram.0 | 2020-03-11 14:45:29.959 | debug | (7381) States create System PubSub Client
telegram.0 | 2020-03-11 14:45:29.956 | debug | (7381) States create User PubSub Client
telegram.0 | 2020-03-11 14:45:29.934 | debug | (7381) Redis States: Use Redis connection: 127.0.0.1:9000
telegram.0 | 2020-03-11 14:45:29.931 | debug | (7381) objectDB connected
telegram.0 | 2020-03-11 14:45:29.924 | debug | (7381) Objects connected to redis: 127.0.0.1:9001
telegram.0 | 2020-03-11 14:45:29.902 | debug | (7381) Objects client initialize lua scripts
telegram.0 | 2020-03-11 14:45:29.901 | debug | (7381) Objects create User PubSub Client
telegram.0 | 2020-03-11 14:45:29.899 | debug | (7381) Objects create System PubSub Client
telegram.0 | 2020-03-11 14:45:29.893 | debug | (7381) Objects client ready ... initialize now
telegram.0 | 2020-03-11 14:45:29.833 | debug | (7381) Redis Objects: Use Redis connection: 127.0.0.1:9001
telegram.0 | 2020-03-11 14:45:24.940 | info | (367) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
telegram.0 | 2020-03-11 14:45:24.939 | info | (367) terminating
telegram.0 | 2020-03-11 14:45:24.434 | info | (367) Got terminate signal TERMINATE_YOURSELF
```

**Comment by pidelta42** [comment]
Hello, it was very similar for me. I've been trying for a while. I opened the bot in telegram and sent a message to the iobroker. (any text) 
Then the bot asked me "Please enter the password:" After I entered it, everything works as before.

**Comment by GermanBluefox** [comment]
PLease reenter the password
