### ISSUE TITLE
recipients are unknown

### ISSUE THREAD

**Issue by afle** [iobroker-community-adapters/ioBroker.telegram#146]
Hi,

since update to version 1.5.5 messages are not send, when using username.
A simple example like this:

```
sendTo('telegram.0', {
    user: 'username',
    text: 'test message'    
});
```

produces an error message in logfile: 
"1 of 1 recipients are unknown!"

Following examples are working:

```
sendTo('telegram.0', {
    chatId: '12345678',
    text: 'test message'    
});
```

```
sendTo('telegram.0', {
    text: 'test message'    
});
```

**Comment by GermanBluefox** [comment]
please activate the "Store username instead of firstname of remembered users" option in instance configuration dialog
