### ISSUE TITLE
/setuserpic is not working

### ISSUE THREAD

**Issue by UncleSamSwiss** [iobroker-community-adapters/ioBroker.telegram#147]
Perhaps I'm missing something, but I tried all ways I could think of to set the user picture:

![image](https://user-images.githubusercontent.com/7595126/78669309-5dcbd880-78dc-11ea-9c3d-e0e2b2613669.png)
![image](https://user-images.githubusercontent.com/7595126/78669403-7e942e00-78dc-11ea-9174-cc9e1d398594.png)

The bot still shows the "initials" colored circle icon.

**Comment by UncleSamSwiss** [comment]
Actually it turns out the documentation is a bit misleading: could you perhaps add a sentence explaining that the `/setuserpic` command must be executed in BotFather, not in the bot conversation (as it is below the `/p` command, I was thinking I needed to do it in the bot conversation).

**Comment by GermanBluefox** [comment]
Done

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/80210000-48bcac80-8633-11ea-91b1-e23e4c2cc157.png)
