### ISSUE TITLE
Set correct connection-status when offline

### ISSUE THREAD

**Issue by Huebeni** [iobroker-community-adapters/ioBroker.telegram#150]
Telegram Plugin 1.4.3
Unfortunately I currently have some problems with my internet connection. So telegram can't connect to the server.
In the logs I see the message "telegram.0 (8940) polling_error:EFATAL, EFATAL: Error: read ECONNRESET". 
BUT: the status of the adapter still tells "Connected to telegram" which is not true.
I suggest setting the status according to the real state.
From my point of view this issue is connected to issue #103 
In this case I would be able to use alternate methods to contact the user or just cache the messages.
Now they are just lost.

Summary: Set the adapter status to "Connected to telegram" only if servers are reachable.

**Comment by GermanBluefox** [comment]
PLease test in 1.5.6
