### ISSUE TITLE
(864) adapter.getMessage is deprecated and will be removed in js-controller 3.0. Please report this warning to the developer of this adapter!

### ISSUE THREAD

**Issue by jh2k19** [iobroker-community-adapters/ioBroker.telegram#151]
Ich Versuche erfolglos per telegram einen Homematic State im ioBroker zu schalten.
Im Log kommt immer diese Meldung:
 "(864) adapter.getMessage is deprecated and will be removed in js-controller 3.0. Please report this warning to the developer of this adapter!"
Woran kann das liegen?

**Comment by GermanBluefox** [comment]
Welche telegram Version?

**Comment by jh2k19** [comment]
Es handelt sich hierbei um die Version 1.4.3.
Ich habe allerdings auch auf einer anderen Installation die Version 1.5.5.
Auch hier habe ich Probleme mit dem schalten von Homematic Datenpunkten. Manchmal wird der Städte geschaltet, meistens geht's nicht. Bei einem Tuya-Adapter Datenpunkt klappt es hingegen problemlos. Was kann das nur sein?

**Comment by GermanBluefox** [comment]
In 1.5.5 ist schon gefixt.

**Comment by GermanBluefox** [comment]
Für Homematic bitte neuen Issue anlegen
