### ISSUE TITLE
(936) adapter.getMessage is deprecated and will be removed in js-controller 3.0. Please report this warning to the developer of this adapter!

### ISSUE THREAD

**Issue by apollo40** [iobroker-community-adapters/ioBroker.telegram#153]
Is it possible to fix this. I dont wanna lose the Telegram feature.

**Comment by Apollon77** [comment]
The latest version should already have it fixed

**Comment by X3m2010** [comment]
I am using adapter version 1.4.3 and still get this warning in the log. So ist this not the latest version?

**Comment by Apollon77** [comment]
latest is 1.5.x
