### ISSUE TITLE
EAI_GAIN Error in Logfile

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.telegram#154]
found these in my log file:

telegram.0 | 2020-04-29 19:51:10.949 | error | (2776) RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org     at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)     at Request.plumbing.callback (/opt/
-- | -- | -- | --
telegram.0 | 2020-04-29 19:51:10.944 | error | (2776) uncaught exception: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org

Anything I can do about this?

**Comment by Apollon77** [comment]
Check your DNS settings and name lookup for domain names. Ethos error says that telegram.org can not be looked up into an IP

**Comment by daniel-lo** [comment]
thanks .. no more of these for a while .. maybe my internet was problematic
