### ISSUE TITLE
Adapter sends the same message many times after a while

### ISSUE THREAD

**Issue by eRaz3r** [iobroker-community-adapters/ioBroker.telegram#157]
Since a while the Telegram-Adapter sends several equal Messages when a script is running. For example:
![Buero](https://user-images.githubusercontent.com/8236933/81157241-0fffca00-8f87-11ea-83e5-1daae1301bea.png)
Door is open, Telegram sends "Door Open". After a while, it sends the Message twice when the door is opened, after another while there are three messages and so on and so on. I have no idea what this issue is about. The log doesn't help me out. Only that the warning (see the attachment) appears also three times. 
![Log_Telegram](https://user-images.githubusercontent.com/8236933/81156907-b8f9f500-8f86-11ea-9e26-cfc9be462e94.png)

I really hope that someone can help me cause it is really annoying.

Thanks a lot

**Comment by Apollon77** [comment]
How the script get started? Maybe add logging to see if and how ofter the script gets started? Maybe this is the case?

**Comment by eRaz3r** [comment]
> How the script get started? Maybe add logging to see if and how ofter the script gets started? Maybe this is the case?

Will do that and report. Thanks

**Comment by eRaz3r** [comment]
So after check the log, the script starts only once. But for example, the warning message 

> (29762) adapter.getMessage is deprecated and will be removed in js-controller 3.0. Please report this warning to the developer of this adapter!

also appears twice. I don't know what to do.

**Comment by Apollon77** [comment]
Plese update to the "Latest" version or to GitHub. Does it happen there too?

**Comment by eRaz3r** [comment]
For now it seems to be okay after I switched to the latest release over GitHub. Will see if this persist. Thanks for your support and your work @Apollon77 !

**Comment by eRaz3r** [comment]
The problem is not solved for me. After a few days, the messages are send multiple times again.
