### ISSUE TITLE
Send message via Response field with Username -  Failed

### ISSUE THREAD

**Issue by Osrx** [iobroker-community-adapters/ioBroker.telegram#167]
From description:
_You can send message over state too, just set state "telegram.INSTANCE.communicate.response" with value "@userName Test message"._

This functionality stop working.
Adapter version: 1.5.9

I Try to send message to myself via request string "@MyUserName Hello Text"

Option "Store username instead of first name of remembered users" checked
and my user is registered and have visible chatID and username it adapter interface.

This functionality used via Node-Red, and this is the only way to send private message.

**Comment by blazeis** [comment]
telegram.0 | 2020-06-23 10:30:11.026 | error | at processImmediate (internal/timers.js:456:21)
-- | -- | -- | --
telegram.0 | 2020-06-23 10:30:11.026 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5388:34)
telegram.0 | 2020-06-23 10:30:11.026 | error | at Adapter.emit (events.js:310:20)
telegram.0 | 2020-06-23 10:30:11.026 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram/main.js:241:21)
telegram.0 | 2020-06-23 10:30:11.026 | error | at sendMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:785:26)
telegram.0 | 2020-06-23 10:30:11.026 | error | (23509) TypeError: users.find is not a function
telegram.0 | 2020-06-23 10:30:11.020 | error | (23509) uncaught exception: users.find is not a function

**Comment by bjoernbusch** [comment]
Any chance that this can be resolved with the associated merge request?

**Comment by Huebeni** [comment]
Hi, the same for me - please merge in master. 
I applied the patch manually on Version 1.5.9. Worked for me. 
Node 12 on Raspberry Pi 4.
