### ISSUE TITLE
Auto-Inline keyboard based on settings in admin (Easy-Keyboard) - /cmds liefert Fehlermeldung

### ISSUE THREAD

**Issue by mwp007** [iobroker-community-adapters/ioBroker.telegram#181]
"/cmds" liefert nix
im LOG:
(5477) Error: ETELEGRAM: 400 Bad Request: field "keyboard" of the ReplyKeyboardMarkup must be an Array of Arrays

bin auf auf stable 1.5.5 zurück , da gehts noch.

LG

**Comment by fincha** [comment]
I have the same issue... maybe reopen it again

**Comment by mwp007** [comment]
seems to be fixed in latest now
thx
