### ISSUE TITLE
Warning text => auf Telegram im Smarthome

### ISSUE THREAD

**Issue by Reuli61** [iobroker-community-adapters/ioBroker.telegram#184]
Hallo, habe das Problem das keine Nachricht mehr durchkommt. Im Log kommt (15790) 1 of 1 recipients are unknown!.
Wo liegt das Problem? Alles wie vorher eingerichtet. Es kommt immer nur diese Meldung Warning. Der Adapter ist der 1.5.9.
Viele Grüße Gisbert

**Comment by Apollon77** [comment]
Mal versucht neu mit dem bot zu verbinden und so?

**Comment by Reuli61** [comment]
Ja, alles probiert. Neuen Bot generiert, es schien das alles funktioniert.
Restartet kam. Und dann die Meldungen. Alles eingestellt wie es sein muß.
War nach einem Update.

Ingo Fischer <notifications@github.com> schrieb am Mi., 16. Sept. 2020,
11:49:
