### ISSUE TITLE
Adapter throws unhandled stacktrace in log: 403 Forbidden: bot can't initiate conversation with a user

### ISSUE THREAD

**Issue by mesche** [iobroker-community-adapters/ioBroker.telegram#185]
I know why the exception occurs and that the exception was originally thrown by "node-telegram-bot-api".
But I would recommend to handle (e.g. with a warning) the exception in the adapter, to avoid that the log is filled up with technical/internal stack informations.

Adapter-Version: 	1.5.9

> telegram.0	2020-09-27 13:49:16.599	error	at processImmediate (internal/timers.js:461:21)
> telegram.0	2020-09-27 13:49:16.599	error	at Immediate.Async.drainQueues [as _onImmediate] (/opt/iobroker/node_modules/bluebird/js/release/async.js:15:14)
> telegram.0	2020-09-27 13:49:16.599	error	at Async._drainQueues (/opt/iobroker/node_modules/bluebird/js/release/async.js:102:5)
> telegram.0	2020-09-27 13:49:16.599	error	at _drainQueue (/opt/iobroker/node_modules/bluebird/js/release/async.js:86:9)
> telegram.0	2020-09-27 13:49:16.599	error	at _drainQueueStep (/opt/iobroker/node_modules/bluebird/js/release/async.js:93:12)
> telegram.0	2020-09-27 13:49:16.599	error	at Promise._settlePromises (/opt/iobroker/node_modules/bluebird/js/release/promise.js:729:18)
> telegram.0	2020-09-27 13:49:16.599	error	at Promise._settlePromise0 (/opt/iobroker/node_modules/bluebird/js/release/promise.js:649:10)
> telegram.0	2020-09-27 13:49:16.599	error	at Promise._settlePromise (/opt/iobroker/node_modules/bluebird/js/release/promise.js:604:18)
> telegram.0	2020-09-27 13:49:16.599	error	at Promise._settlePromiseFromHandler (/opt/iobroker/node_modules/bluebird/js/release/promise.js:547:31)
> telegram.0	2020-09-27 13:49:16.599	error	at tryCatcher (/opt/iobroker/node_modules/bluebird/js/release/util.js:16:23)
> telegram.0	2020-09-27 13:49:16.599	error	at /opt/iobroker/node_modules/node-telegram-bot-api/src/telegram.js:283:15
> telegram.0	2020-09-27 13:49:16.599	error	(533) Error: ETELEGRAM: 403 Forbidden: bot can't initiate conversation with a user
> telegram.0	2020-09-27 13:49:16.599	error	(533) unhandled promise rejection: ETELEGRAM: 403 Forbidden: bot can't initiate conversation with a user
> Unhandled	2020-09-27 13:49:16.599	error	promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

Regards
Esche

**Comment by Apollon77** [comment]
The problem is that it is thrown  by the lib in a way that it is not catchable :-( see https://github.com/yagop/node-telegram-bot-api/issues/798 :-(
