### ISSUE TITLE
resolv.conf und iobroker - telegram vertragen sich nicht

### ISSUE THREAD

**Issue by Homie13** [iobroker-community-adapters/ioBroker.telegram#189]
Hallo zusammen,
seit einiger Zeit habe ich Probleme, das Telegram nicht richtig funktioniert.
Der Grund ist ich habe in meiner Fritzbox v7.21 die DNS-Server von Cloudflare 1.1.1.1 und 1.0.0.1
und DNS over TLS eingetragen.
In meiner resolv.conf ist als nameserver 127.0.0.53 eingetragen. Hiermit bleibt der Telegram Adapter
immer rot. Wenn ich dann in der resolv.conf die Cloudflare DNS eintrage funktioniert der Adapter
wieder. Nach einem Neustart von iobroker jedoch funktioniert es leider nicht mehr.
Iobroker läuft in einer VM unter Ubuntu.
Es wäre schön, wenn man den Fehler beheben könnte.
Die anderen Adapter funktionieren einwandfrei, ohne das ich die resolv.conf ändern muss.
Vielen Dank für eure Mühe im voraus.

**Comment by Apollon77** [comment]
Was steht im Log?

**Comment by Homie13** [comment]
![Log-iobroker](https://user-images.githubusercontent.com/32713567/96512376-b0f5ef00-1260-11eb-8c13-72312c12d014.png)
Dies hier.

**Comment by Apollon77** [comment]
Ich sehe keinen Weg was der Adapter hier tun kann. der Fehler bedeutet das das DNS lookup aus dem Nodejs Prozess nicht tut ...

**Comment by Homie13** [comment]
Okay, ich meine irgenwo gelesen zu haben, das node und js-controller die gleiche Version sein sollen. Kann es damit zusammenhängen? Wenn ja wei bekomme ich den auf die gleiche Version?

**Comment by Apollon77** [comment]
ääähmm . hä ?! Ich habe keine Ahnugn was das sein soll.

An sich nutzt nodejs genau das gleiche DNS was im system genutzt wird. also am besten mal mit den sondereinstellungen ein "ping api.telegram.org" versuchen. Geht das? Wenn nein ... das fixen

**Comment by Homie13** [comment]
Temporärer Fehler bei der Namensauflösung....
Wie kann ich es fixen?
Ich hatte in meinem ersten Posten geschrieben, das in der resolv.conf
nur die 127.0.053 eingetragen ist. Damit funktioniert die Namensauflösung nicht. Wenn ich den richtigen Nameserver eintrage dann funktioniert es bis zum nächsten Neustart, dann nicht mehr. Ich habe iobroker unter Ubuntu 18.04 installiert.
Wie kann ich das fixen?

**Comment by Apollon77** [comment]
Sorry, aber das ist eine Linux support Frage und hat mit dem Adapter nichts zu run. Bitte im Forum nachfragen bzw in einschlägigen Foren zu dem Thema. Ich kann Dir da nicht weiterhelfen
