### ISSUE TITLE
Conditional sending of state changes

### ISSUE THREAD

**Issue by HSE83** [iobroker-community-adapters/ioBroker.telegram#190]
Hi,

unfortunately right now I can't really use the "state change" notification since there are two major drawbacks:
First, it seems that any state _update_ triggers a message being sent, regardless whether the new value is equal to the old one. At least I get repeated messages telling me the exact same state value for the same object (repeated in even intervals, probably the owning adapter's update rate of the state).
Secondly I would greatly appreciate a feature to filter the messages being sent out by the new value reached by a state (basically "export" the conditions the Javascript "on" notifier already provides for filtering).

Please let me know if there is a way this could be realized.

Best regards,
Tobi

**Comment by Andrey2509** [comment]
I confirm the problem. The logic should be like in the sql driver. It is necessary to react to changes in the value of the object, not the object itself.

**Comment by Anzic23** [comment]
+1
