### ISSUE TITLE
Telegram instance crashes when sending a message to a specific user

### ISSUE THREAD

**Issue by Huseriato** [iobroker-community-adapters/ioBroker.telegram#194]
**To Reproduce**  
Put a text beginning with a username in path `telegram.0.communicate.response`.

**Expected behavior**  
Sending a message to a specific user.

**Screenshots & Logfiles**  

```
telegram.0 | 2020-11-25 16:33:17.211 | info | (16385) Terminated (NO_ERROR): Without reason
telegram.0 | 2020-11-25 16:33:17.209 | info | (16385) terminating
telegram.0 | 2020-11-25 16:33:16.702 | error | at processImmediate (timers.js:658:5)
telegram.0 | 2020-11-25 16:33:16.702 | error | at tryOnImmediate (timers.js:676:5)
telegram.0 | 2020-11-25 16:33:16.702 | error | at runCallback (timers.js:705:18)
telegram.0 | 2020-11-25 16:33:16.702 | error | at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5388:34)
telegram.0 | 2020-11-25 16:33:16.702 | error | at Adapter.emit (events.js:198:13)
telegram.0 | 2020-11-25 16:33:16.702 | error | at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.telegram/main.js:241:21)
telegram.0 | 2020-11-25 16:33:16.702 | error | at sendMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:784:26)
telegram.0 | 2020-11-25 16:33:16.702 | error | (16385) TypeError: users.find is not a function
telegram.0 | 2020-11-25 16:33:16.698 | error | (16385) uncaught exception: users.find is not a function
```

**Versions:**  
 - Adapter version: 1.5.9
 - JS-Controller version: 3.1.6
 - Node version: 10.23.0
 - Operating system: Raspbian GNU/Linux 10 (buster) - 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux

**Comment by Apollon77** [comment]
Please try 1.6.0 from Github or latest repo. Fixed there?

**Comment by Huseriato** [comment]
I used the official update via iobroker. Version 1.6.0 just released.

It's not crashing anymore, but there is no message send (and there is no error in the log file). I'm using the exact username copied via ctrl+c/ctrl+v of the `telegram.0.communicate.users` path. There is just one user.

It seems so, that someone added a try { } catch around the bug, but did not handle it correctly.

**Comment by Huseriato** [comment]
Okay, I tried a little bit more. You have to check the following option

![image](https://user-images.githubusercontent.com/14014947/100355671-75cea480-2ff2-11eb-89e6-e24fdb578517.png)

to make it possible to send to usernames. Instead you have to use firstnames (which will not work for us, because there multiple users with the same name, after the setup is finished). I don't know, what this options originally in english, but the german translation does not make any sense for what it is doing.

Better might be: "Usernamen anstelle des Vornamens für direkte Nachrichtenzustellung verwenden" - but I'm not sure, if there are other functions in the telegram adapter that are using this option.

**Comment by Huseriato** [comment]
The translation is still wrong and the crash does still exist.

**Comment by Apollon77** [comment]
Pleas einstall most up to date verison from latest or Github and provide new log please
