### ISSUE TITLE
The documentation of this adapter could be greatly improved

### ISSUE THREAD

**Issue by zaunermax** [iobroker-community-adapters/ioBroker.telegram#196]
As the title says, the documentation could be greatly improved, by giving users a heads up on turning the log level to debug if they want to find out about the `chat_id` of a chat, as the adapter empties the `/getUpdates` endpoint.

My usecase was to send messages to different groups, which I could not read in the readme of this adapter.

If you want, I can try and write some documentation and make a PR if that is ok?

Thanks for maintaining this awesome adapter :rocket:

**Comment by Apollon77** [comment]
We are happy to take PRs - especially for documentation "from a users point of view".
