### ISSUE TITLE
Fehlermeldung nach Update auf 1.6.0

### ISSUE THREAD

**Issue by dslraser** [iobroker-community-adapters/ioBroker.telegram#197]
Nach/seit Update auf 1.6.0 bekomme ich Fehlermeldungen im Log (Bild versenden nach klingeln)
`

telegram.0 | 2020-12-01 11:17:13.226 | error | (16045) Cannot send photo [chatId - xxxxxx]: Error: ETELEGRAM: 400 Bad Request: IMAGE_PROCESS_FAILED
-- | -- | -- | --

`

Das Bild wird aber dennoch erfolgreich versendet. Die Fehlermeldung erscheint 2x für die gleiche Chat ID.

EDIT: zurück auf 1.5.9 erfolgt der Versand ohne Fehlermeldung
`

javascript.0 | 2020-12-01 11:36:45.599 | info | (6068) script.js.06_Klingel_und_Summer.Klingel-Telegram-Bild-Eingang: Snapshot sent
-- | -- | -- | --

`

**Comment by crunchip77** [comment]
Diese Error Meldung habe ich seit heute auch, allerdings hatte mein Script mit 1.6.0 noch funktioniert, erst seit 1.6.1 das Problem. Ebenfalls hatte ich Javascript von 4.10.6 auf 4.10.8 upgedatet.
Ich bin mit Javascript, sowie Telegram, mehrere Versionen zurück, IoBroker auch zwischenzeitlich neu gestartet. Error Meldung kommt aber nach wie vor und Bild wird nicht versendet. Nachdem ich im entsprechenden Ordner nachgesehen habe, ist das Bild zwar vorhanden, kann dieses aber nicht öffnen, **falsches Dateiformat**
