### ISSUE TITLE
massive amount of requests to api.telegram.org from telegram adapter every night at four/ adapter polling this host frequently

### ISSUE THREAD

**Issue by m4ding** [iobroker-community-adapters/ioBroker.telegram#199]
I have the newest version of telegram running in up to date iobroker. In my pihole instance, I can see that every night at four, about 5.500 requests are sent to api.telegram.org. 

I have observed this behavior some time ago when no other adapter used telegram on my io instance. Now, I only use backitup to inform me about a sucessful backup. 

![IMG_1030](https://user-images.githubusercontent.com/65028008/101137077-8a242a00-360e-11eb-8eff-b9376a974540.jpg)
![IMG_1031](https://user-images.githubusercontent.com/65028008/101137081-8b555700-360e-11eb-970d-c8c0e5c817fa.jpg)
![IMG_1032](https://user-images.githubusercontent.com/65028008/101137088-8c868400-360e-11eb-8ed4-f8b24a507c51.jpg)

**Comment by Apollon77** [comment]
could it be that you have an adapter restart of the telegram adapter at 4:00? This was a standard setting sometimes. SO ... whats ioBroker Log showing at 4:00?

**Comment by m4ding** [comment]
Thanks, I'll have a look!
