### ISSUE TITLE
Error: "ETELEGRAM: 403 Forbidden: bot was blocked by the user"

### ISSUE THREAD

**Issue by apla2016** [iobroker-community-adapters/ioBroker.telegram#204]
Telegram was working fine but recently I started to get error messages 
Cannot send message [chatId - 505191441]: Error: ETELEGRAM: 403 Forbidden: bot was blocked by the user

Here my logic (not changed recently)
![image](https://user-images.githubusercontent.com/19657413/106060026-8cac7880-60c1-11eb-9e80-662a0dd1817f.png)

I have telegram adapter 1.7.0
Node.js v12.19.0
Controller 3.2.11

**Comment by Apollon77** [comment]
Try re-setup the bot user ... becase error says that the user blocked the bot as it seems

**Comment by apla2016** [comment]
In Telegram application on my PC I found a way to restart the bot and everything is working now. Thank you.

**Comment by apla2016** [comment]
I reset bot within PC Telegram application and everything works now. Thank you.

Anatoly
