### ISSUE TITLE
"Last message sent out" in Object-Tree

### ISSUE THREAD

**Issue by jhnnsngl** [iobroker-community-adapters/ioBroker.telegram#210]
In The Object-Tree I can see "Last received request" - which is the last massage **I send to the Bot**.

I wish I could also have an object which is the **last message sent out by the bot**.
I want to react on massage from the bot - which were sent from any source (Iobroker, API).
The use case I have: My phone sents out an API Massage to the Telegram-Bot when my Smartphone Batterie is completly full - at this moment I want to disable the power plug.

**Comment by jhnnsngl** [comment]
Noby can help. I´ll gess there will be more use cases ?

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/123509027-75bf8180-d673-11eb-9e13-6786179f4aec.png)

I think, that is what you need.
