### ISSUE TITLE
chatId recipient is treated as user. can't send message

### ISSUE THREAD

**Issue by sinky** [iobroker-community-adapters/ioBroker.telegram#214]
**Describe the bug**  
If the Recipient is a group (eg. "-12345678") and is not set directly on the block by a string block, the given group is treated as "user" parameter and not "chatId".

**To Reproduce**  
1. add a telegram sendto block
2. add a string block with "-12345678" (chatID) as recipient
3. switch to javascript and see function parameter is "chatId"
4. switch back to blocky and replace the recipient with a variable containing the string "-12345678"
5. switch to javascript and see function parameter now is "user"

**Expected behavior**  
If the chatId is give by variable or "Value of Object"-Block the resulting javascript function should have the chatId parameter and not user parameter 

**Screenshots & Logfiles**  
N/A

**Versions:**  
 - Adapter version: 1.8.0
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system: Raspbian GNU/Linux 10

**Comment by ChristianB86** [comment]
Hello, same problem here. You also can't use the chat-id from a user. This won't work even if you put the chat-id direct (as Text) on the sendTo-Block. 

![issue](https://user-images.githubusercontent.com/66794858/115953299-ec60c700-a4ea-11eb-9659-9b3dd52a5432.png)

This results in:

```
sendTo("telegram", "send", {
    text: 'text',
    user: '123456789'
});

group_id = '-1234567890123';
sendTo("telegram", "send", {
    text: 'text',
    user: group_id
});
```

As you said, the option 'user' has to be 'chatId'

**Comment by Apollon77** [comment]
I think "Empfänger" here explicitely means a user ... so we should simply add another blockly parameter for the chatId and generate code correctly to send as chatId. I think chatId was added but blockly was not also enhanced. This is the natural solution :-)

**Comment by ChristianB86** [comment]
There is code in blockly.js that determinate if "Empfänger" (Username) is a chat-id or not. But it only works for "hardcoded" group-chat-ids (beginns with "-"). Adding a new blockly parameter should be a clean solution. I can do this, but i can't do all the translations.

BTW: The telegram-bot API does not support sending messages to usernames at all. You can only use chat-ids. The Adapter stores chat-ids and asigned usernames if you enable it in the settings

**Comment by Apollon77** [comment]
Translation is easy :-))
use https://translator.iobroker.in/
