### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.telegram#218]
telegram 1.8.0
js-controller 3.2.16
nodejs 12.22.0

no internet force reconnect or network issues at this moment

> 2021-04-06 11:56:28.488 - error: telegram.0 (1930) getMe Error:Error: EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
> 2021-04-06 11:56:28.490 - error: telegram.0 (1930) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> 2021-04-06 11:56:28.490 - error: telegram.0 (1930) unhandled promise rejection: EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
> 2021-04-06 11:56:28.491 - error: telegram.0 (1930) RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
> at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
> at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
> at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
> at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
> at Request.emit (events.js:314:20)
> at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
> at ClientRequest.emit (events.js:314:20)
> at TLSSocket.socketErrorListener (_http_client.js:427:9)
> at TLSSocket.emit (events.js:314:20)
> at emitErrorNT (internal/streams/destroy.js:92:8)
> at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 2021-04-06 11:56:28.491 - error: telegram.0 (1930) Exception-Code: EFATAL: EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
> 2021-04-06 11:56:29.109 - info: telegram.0 (1930) terminating
> 2021-04-06 11:56:29.109 - warn: telegram.0 (1930) Terminated (UNCAUGHT_EXCEPTION): Without reason
> 2021-04-06 11:56:29.671 - error: host.iobroker instance system.adapter.telegram.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by Apollon77** [comment]
Please enable debug log and provide when happens next time ... I need to know what as tried to be called ... we hoped to have catched all cases on last update, but seems we missed one

**Comment by Diginix** [comment]
Tricky to run the instance the whole time with loglevel debug without knowing when it will happen again.
Today it was after a reboot of the whole server, but the network was already established/present.

**Comment by GermanBluefox** [comment]
Should be fixed with 1.8.3
