### ISSUE TITLE
Add support for editMessageMedia

### ISSUE THREAD

**Issue by Xyolyp** [iobroker-community-adapters/ioBroker.telegram#226]
Add support for `editMessageMedia`

**Describe the solution you'd like**
I would like to be able to exchange a picture I sent using the telegram bot to display a more recent version of it. (3D Printer Webcam)

Currently I'm deleting the sent picture and sending a new one but this causes a new notification on my phone and desktop (without sound as I set the disableNotification parameter)

**Comment by GermanBluefox** [comment]
Added in 1.8.3 (See readme)
