### ISSUE TITLE
unauthorized user can access keyboard

### ISSUE THREAD

**Issue by edyso** [iobroker-community-adapters/ioBroker.telegram#246]
**Describe the bug**  
an unauthorized user can access the keyboard.

**To Reproduce**  
1. start a new chat with the bot
2. send the keyboard-command, default /cmnd, or help-command /help
3. user can see the keyboard and control it

**Expected behavior**  
user should enter password first to be authenticated and to get access.

**Versions:**  
 - Adapter version: 1.8.1
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: linux x64, debian   @@buster

**Additional context**  
<a href="https://ibb.co/M27GwMG"><img src="https://i.ibb.co/M27GwMG/Screenshot-2021-06-21-10-27-55-154-org-telegram-messenger.jpg" alt="Screenshot-2021-06-21-10-27-55-154-org-telegram-messenger" border="0"></a>

**Comment by GermanBluefox** [comment]
Fixed in 1.8.3
