### ISSUE TITLE
Notification only in case of change does not work (wrench symbol object list)

### ISSUE THREAD

**Issue by Domi920** [iobroker-community-adapters/ioBroker.telegram#252]
If you click the wrench for a data point in the object list, you can send an automatic telegram notification when the data point is updated.

 Unfortunately the notification is also sent if the value has only been updated (not changed).
 No matter what settings you make.

**Comment by tmycgn** [comment]
Same issue.

I cannot define in the settings that a message is sent only when the value is changed. Therefore, when I set a false to false a message is sent. But this should not happen.

```
Raspbian GNU/Linux 10 (buster)
Admin 5.3.3
NPM 6.14.14
Node.js v14.19.1
js-controller 4.0.21
Telegram Adapter v1.12.0
```

**Comment by Apollon77** [comment]
@tmycgn Please open a new issue, show configuration and provide a debug log from such an "value change"
