### ISSUE TITLE
Anruf über telegram funktioniert nicht

### ISSUE THREAD

**Issue by hardl1** [iobroker-community-adapters/ioBroker.telegram#258]
**Describe the bug**  
Egal ob über Blockly oder JS-Skript erfolgt kein Anruf, im Protokoll steht:
`

telegram.0 | 2021-08-23 14:48:28.429 | warnen | TypeError: Zuweisung an konstante Variable. at callUsers (/opt/iobroker/node_modules/iobroker.telegram/main.js:1262:15) at processMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:1247:21) at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram/main.js:155:17) bei Adapter.emit (events.js:314:20) bei Änderung (/opt/iobroker/node_modules/iobroker.js-controller/lib /adapter.js:5634:34) bei Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:232:37) bei processImmediate (internal/timers.js .) :461:21)
-- | -- | -- | --
telegram.0 | 2021-08-23 14:48:28.428 | warnen | Zustände system pmessage io.messagebox.system.adapter.telegram.0 {"command":"call","message":{"text":"achtung","user":"@xxx","language":" de-DE-Standard-A","users":[],"lang":"de-DE-Standard-A","message":"achtung"},"from":"system.adapter.javascript. 0","_id":19661887} Zuweisung zu konstanter Variable.

**To Reproduce**  
`sendTo('telegram.0', 'call', {
 
    text: 'achtung',
 
    user: '@xxx',
 
    language: 'de-DE-Standard-A' // optional
 
});`

**Expected behavior**  
Anruf über telegram

**Versions:**  
 - Adapter version: 1.10.0
 - JS-Controller version: 3.3.15
 - Node version: 12.22.2
 - Operating system: OS Big-sur 11.5.2

**Additional context**  
Sprachnachrichten über telegram funktionieren problemlos

**Comment by lkn94** [comment]
I can confirm this issue. Reproduced yesterday 08/28/2021.

**Comment by Theboss996** [comment]
Guten abend ich denke ich habe das selbe oder gleiche problem was mache ich flasch bzw wie kann ich mein Problem beheben...????? 

beste Grüße 

Silvan



telegram.0 | 2021-09-02 19:14:05.930 | warn | TypeError: Assignment to constant variable. at callUsers (/opt/iobroker/node_modules/iobroker.telegram/main.js:1262:15) at processMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:1247:21) at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram/main.js:155:17) at Adapter.emit (events.js:314:20) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5634:34) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:232:37) at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
telegram.0 | 2021-09-02 19:14:05.930 | warn | States system pmessage io.messagebox.system.adapter.telegram.0 {"command":"call","message":"Some text","from":"system.adapter.javascript.0","_id":62821592} Assignment to constant variable.


</body>
</html>

**Comment by lkn94** [comment]
Das ist genau das gleiche Problem. Zur Behebung müssen die Entwickler ran. Daher auch das Issue ;)

**Comment by rmp63526** [comment]
Hello, same issue i have here too with the same error code. 
Please thumbs up in the first post, (Hardl1) it make it easier for the developer.

**Comment by winnyschuster** [comment]
error comes from assigning a value to **constant axios** [here](https://github.com/iobroker-community-adapters/ioBroker.telegram/blob/feab216e4b5c4bacf72263689abb0922f83f28be/main.js#L1262) which is defined [here](https://github.com/iobroker-community-adapters/ioBroker.telegram/blob/feab216e4b5c4bacf72263689abb0922f83f28be/main.js#L27)

Tested solution: either comment out line 1262 or define axios with **let** instead of **const** in Line 27

**Comment by ghifunk** [comment]
Hallo,
ich komme auch nicht weiter, habe die gleichen Fehlermeldungen im Protokoll!
Wäre schön, wenn sich die Entwickler dessen nochmal annehmen würden
Gruß
ghifunk

**Comment by liv-in-sky** [comment]
**für den entwickler** - die lösung für die änderung im adapter wird heir erwähnt - danke an @fastfood

https://forum.iobroker.net/post/697310
