### ISSUE TITLE
Add communication status for sending silent requests without notification (communicate.responseSilent) using Telegram Bot API disable_notification 

### ISSUE THREAD

**Issue by mghomedev** [iobroker-community-adapters/ioBroker.telegram#270]
We have different use cases for Telegram Bots:

1. Logging/Tracing for normal status changes (e.g. Startup / Shutdown messages every night during backups)
2. Alerts/Warnings e.g. when a measurement number becomes too low (heating system breaks)

The human that gets the messages only wants notfications on their phone when its an Alert/Warning (2.), but does not want them in normal logging/tracing circumstances (1.).

Therefore, we should be able to take advantage of the "disable_notification" API option see https://core.telegram.org/bots/api#available-methods or  https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_message

1. The Startup/Shutdown messages should be configurable to be silent, i.e. disable_notification=true . Furthermore, a new status communicate.responseSilent should be created to allow easy sendign silent status with disable_notification=true . 
2. The existing communication status "communicate.response" can then be used to trigger notifications on mobile phones for errors. You could also add a status "communicate.responseNotify" to enforce disable_notification=false

**Comment by GermanBluefox** [comment]
Added responseSilent  in 1.11.0
