### ISSUE TITLE
create keyboard without answer

### ISSUE THREAD

**Issue by Xenon-s** [iobroker-community-adapters/ioBroker.telegram#271]
**Is your feature request related to a problem? Please describe.**
Currently, it is mandatory to enter a response text if you want to create a keyboard. Is it possible to work around this, so does the API even allow it? Or is this not possible?

**Describe the solution you'd like**
Create keyboard without the bot answering every time

**Comment by GermanBluefox** [comment]
> so does the API even allow it?

Can you find it out?
