### ISSUE TITLE
Kein anzeigen der Räume

### ISSUE THREAD

**Issue by Zentauer** [iobroker-community-adapters/ioBroker.telegram#272]
Hallo,

obwohl die Checkbox bei "Räume in Tastaturbefehl verwenden" angehakt ist, werden im Chat trotzdem sofort alle Geräte angezeigt.
Alle meine Geräte sind einem Raum zugewiesen.

![image](https://user-images.githubusercontent.com/35875079/138953993-90fec539-09e3-486f-b699-788168b46130.png)

**Versions:**  
 - Adapter version: v1.10.0
 - JS-Controller version: v3.3.18
 - Node version: v12.22.7
 - Operating system: linux

**Comment by GermanBluefox** [comment]
Screenshot?

**Comment by Zentauer** [comment]
`Screenshot?`
Von was brauchst du einen?

Wenn ich diese Checkbox aktiv habe müssten dann nicht erst die Räume im Telegrammenü kommen vor den Geräten?
Bei mir macht es keinen unterschied ob diese Option aktiviert ist oder nicht. Es kommen nur meine Geräte in der Liste ohne die Räume davor.

**Comment by Nahasapeemapetilon** [comment]
als workaround kannst du mein telegrammenü verwenden :
