### ISSUE TITLE
get messageID/chatID in response of sendto()

### ISSUE THREAD

**Issue by tetzlav** [iobroker-community-adapters/ioBroker.telegram#280]
I use the telegram adapter to send snapshots and videos of our surveillance cameras.
At camera event at first i send a snapshot, record a 30s video and than i edit the first message and replace snapshot with video to save the overview in the chat.

It is a bit laborious to handle the messageIDs in case of more than one user.

Is it possible, to get the messageID/chatID of the actual send message in the response objekt of sendTo?
What i want is something like this:

```
return new Promise((resolve) => {
        sendTo('telegram.0', {
            [...]
        }, (res) => resolve(res));
}

for (var i = 0; i < res.users; i++) {
        log(res.chatid[i])
        log(res.messageid[i]
}
```

Is it possible?

**Comment by boergegrunicke** [comment]
Nothing happened for a long time on this, but it would be helpful for me as well.
I am sending many messages to myself via telegram. (coffee ready, vacuuming robot started/finished, ...). To clean up the chat history and put more focus on really relevant messages, I want to delete messages that do not need to stay permanently. 
Reading the message id from `telegram.0.communicate.botSendMessageId` in the callback function of `sentTo` unfortunately is bringing wrong results too often. Especially when multiple messages are sent in a short amount of time. Getting the feedback of the actual message id in the callback function would be very helpful to get it working correctly.
