### ISSUE TITLE
sendMediaGroup

### ISSUE THREAD

**Issue by hdering** [iobroker-community-adapters/ioBroker.telegram#29]
Ist versuche über telegram ein PhotoAlbum zu verschicken.

Laut API Spezifikation ist die Funktion sendMediaGroup dafür gedacht (https://core.telegram.org/bots/api/#).

Meine Idee war wie folgt:

```
var mediastring = "{type: 'photo', media: '/tmp/camera.jpg' }, {type: 'photo', media: '/tmp/camera.jpg' }, {type: 'photo', media: '/tmp/camera.jpg'}";

// JSON serialize
var meineBilder = JSON.stringify(mediastring);
var obj = JSON.parse(meineBilder);

sendTo("telegram.0", {
    text: 'mediagroup',
    chatId: 398694033,
    media: obj,
});
```

Ich bekomme in telegram App nur den Text "mein Text" angezeigt, aber nicht die Bilder.

Laut der Spezifikation (siehe den Link oben) soll man auch nur die chatid und media angeben. Wenn ich "text" weg lasse, erhalte ich aber folgende Fehlermeldung im iobroker log:
telegram.0	2018-01-26 14:45:01.278	error	Cannot send message [user - undefined]: Error: ETELEGRAM: 400 Bad Request: message text is empty

Muss man die den Adapter eventuell abändern, dass er auch ohne den Parameter "text" funktioniert?

**Comment by Haba1234** [comment]
Hi!
The adapter does not yet implement the sendMediaGroup function.

Der Adapter implementiert die sendMediaGroup-Funktion noch nicht.

**Comment by hdering** [comment]
Are you planning to install it?

**Comment by GermanBluefox** [comment]
Done in PR
