### ISSUE TITLE
Unter Version 1.11.0 werden keine Telegram-Nachrichten mehr verschickt.

### ISSUE THREAD

**Issue by vepman** [iobroker-community-adapters/ioBroker.telegram#293]
- Adapter version: 1.11
 - JS-Controller version: 3.3.23
 - Operating system: Linux

Unter Version 1.11.0 werden keine Telegram-Nachrichten mehr verschickt.

Im Log ist kein Vermerk eines Fehlers:
`javascript.0 2022-01-27 08:03:03.409	info	(4203) script.js.common.Message.Skript_1: test
javascript.0	2022-01-27 08:03:02.963	info	(4203) script.js.common.Message.Skript_1: test
javascript.0	2022-01-27 08:02:49.024	info	(4203) script.js.common.Message.Skript_1: registered 1 subscription and 0 schedules
javascript.0	2022-01-27 08:02:49.006	info	(4203) Start javascript script.js.common.Message.Skript_1`

Bei einem Downgrade auf 1.10.1 geht der Adapter wieder und alle Nachrichten werden wieder verschickt.
Nach einem erneuten Upgrade tritt der Fehler wieder auf.
Auch nach einem Neustart des Systems trat der Fehler unter 1.11.0 wieder auf.

**Comment by Apollon77** [comment]
Please provide a debig log from telegram adapter

**Comment by Diginix** [comment]
Same here. No matter if with specific recipient or to all. Rollback to 1.10.0/1 works. Maybe later today I can update again and create a debug log. But 1.11.x shouldn't work for @GermanBluefox as well.

**Comment by vepman** [comment]
Mit Telegram v1.11.0 und v1.10.1
`telegram.0	2022-01-27 08:42:58.843	debug	(9320) Message sent
telegram.0	2022-01-27 08:42:58.842	debug	(9320) Request: {"message_id":70606,"from":{"id":239330127,"is_bot":true,"first_name":"HMBot","username":"HMCCU2bot"},"chat":{"id":242350154,"first_name":"Vep","username":"Vepman","type":"private"},"d
telegram.0	2022-01-27 08:42:58.765	debug	(9320) Send message to "Vep": GEHT
telegram.0	2022-01-27 08:42:58.764	debug	(9320) Received command "send": {"text":"GEHT"}
javascript.0	2022-01-27 08:42:58.752	info	(4203) script.js.common.Message.Skript_1: test
telegram.0	2022-01-27 08:42:58.253	debug	(9320) Message sent
telegram.0	2022-01-27 08:42:58.252	debug	(9320) Request: {"message_id":70605,"from":{"id":239330127,"is_bot":true,"first_name":"HMBot","username":"HMCCU2bot"},"chat":{"id":242350154,"first_name":"Vep","username":"Vepman","type":"private"},"d
telegram.0	2022-01-27 08:42:58.139	debug	(9320) Send message to "Vep": GEHT
telegram.0	2022-01-27 08:42:58.138	debug	(9320) Received command "send": {"text":"GEHT"}
javascript.0	2022-01-27 08:42:58.121	info	(4203) script.js.common.Message.Skript_1: test
telegram.0	2022-01-27 08:42:39.843	debug	(9320) Message sent
telegram.0	2022-01-27 08:42:39.842	debug	(9320) Request: {"message_id":70604,"from":{"id":239330127,"is_bot":true,"first_name":"HMBot","username":"HMCCU2bot"},"chat":{"id":242350154,"first_name":"Vep","username":"Vepman","type":"private"},"d
telegram.0	2022-01-27 08:42:39.784	debug	(9320) Send message to "Vep": Bot gestartet
telegram.0	2022-01-27 08:42:39.779	debug	(9320) getMe: {"id":239330127,"is_bot":true,"first_name":"HMBot","username":"HMCCU2bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}
telegram.0	2022-01-27 08:42:39.515	debug	(9320) Start polling with: 300(number) ms interval
telegram.0	2022-01-27 08:42:39.319	info	(9320) starting. Version 1.10.1 in /opt/iobroker/node_modules/iobroker.telegram, node: v14.18.3, js-controller: 3.3.22
host.buanet-iobroker1	2022-01-27 08:42:37.571	info	iobroker exit 0
host.buanet-iobroker1	2022-01-27 08:42:36.595	info	instance system.adapter.telegram.0 started with pid 9320
host.buanet-iobroker1	2022-01-27 08:42:36.352	info	"system.adapter.telegram.0" enabled
host.buanet-iobroker1	2022-01-27 08:42:36.306	info	iobroker host.buanet-iobroker1 Adapter "system.adapter.telegram.0" is started
host.buanet-iobroker1	2022-01-27 08:42:36.304	info	iobroker Adapter "telegram" updated
host.buanet-iobroker1	2022-01-27 08:42:36.241	info	iobroker upload [0] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/blockly.js blockly.js application/javascript
host.buanet-iobroker1	2022-01-27 08:42:36.182	info	iobroker upload [1] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/custom_m.html custom_m.html text/html
host.buanet-iobroker1	2022-01-27 08:42:36.124	info	iobroker upload [2] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/de/translations.json i18n/de/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:36.066	info	iobroker upload [3] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/en/translations.json i18n/en/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:36.007	info	iobroker upload [4] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/es/translations.json i18n/es/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.949	info	iobroker upload [5] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.890	info	iobroker upload [6] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/it/translations.json i18n/it/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.830	info	iobroker upload [7] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.768	info	iobroker upload [8] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.709	info	iobroker upload [9] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.646	info	iobroker upload [10] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.585	info	iobroker upload [11] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.524	info	iobroker upload [12] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/index.html index.html text/html
host.buanet-iobroker1	2022-01-27 08:42:35.463	info	iobroker upload [13] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/index_m.html index_m.html text/html
host.buanet-iobroker1	2022-01-27 08:42:35.402	info	iobroker upload [14] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/jsonCustom.json jsonCustom.json application/json
host.buanet-iobroker1	2022-01-27 08:42:35.343	info	iobroker upload [15] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/telegram.png telegram.png image/png
host.buanet-iobroker1	2022-01-27 08:42:35.237	info	iobroker Update "system.adapter.telegram.0"
host.buanet-iobroker1	2022-01-27 08:42:35.131	info	iobroker upload [16] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/words.js words.js application/javascript
host.buanet-iobroker1	2022-01-27 08:41:30.890	info	instance system.adapter.telegram.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
telegram.0	2022-01-27 08:41:30.255	info	(8971) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
telegram.0	2022-01-27 08:41:30.254	info	(8971) terminating
host.buanet-iobroker1	2022-01-27 08:41:30.233	info	iobroker npm install iobroker.telegram@1.10.1 --loglevel error --prefix "/opt/iobroker" (System call)
host.buanet-iobroker1	2022-01-27 08:41:30.231	info	iobroker NPM version: 6.14.15
host.buanet-iobroker1	2022-01-27 08:41:29.789	info	stopInstance system.adapter.telegram.0 send kill signal
telegram.0	2022-01-27 08:41:29.752	info	(8971) Got terminate signal TERMINATE_YOURSELF
host.buanet-iobroker1	2022-01-27 08:41:29.740	info	stopInstance system.adapter.telegram.0 (force=false, process=true)
host.buanet-iobroker1	2022-01-27 08:41:29.738	info	"system.adapter.telegram.0" disabled
host.buanet-iobroker1	2022-01-27 08:41:29.672	info	iobroker host.buanet-iobroker1 Adapter "system.adapter.telegram.0" is stopped.
host.buanet-iobroker1	2022-01-27 08:41:29.628	info	iobroker Update telegram from @1.11.0 to @1.10.1
host.buanet-iobroker1	2022-01-27 08:41:27.570	info	iobroker upgrade telegram@1.10.1
telegram.0	2022-01-27 08:38:48.512	debug	(8971) Received command "send": {"text":"GEHT"}
javascript.0	2022-01-27 08:38:48.497	info	(4203) script.js.common.Message.Skript_1: test
telegram.0	2022-01-27 08:38:47.902	debug	(8971) Received command "send": {"text":"GEHT"}
javascript.0	2022-01-27 08:38:47.889	info	(4203) script.js.common.Message.Skript_1: test
telegram.0	2022-01-27 08:38:15.163	debug	(8971) Received command "send": {"text":"GEHT"}
javascript.0	2022-01-27 08:38:15.151	info	(4203) script.js.common.Message.Skript_1: test
telegram.0	2022-01-27 08:38:14.372	debug	(8971) Received command "send": {"text":"GEHT"}
javascript.0	2022-01-27 08:38:14.351	info	(4203) script.js.common.Message.Skript_1: test
javascript.0	2022-01-27 08:38:10.028	info	(4203) script.js.common.Message.Skript_1: registered 1 subscription and 0 schedules
javascript.0	2022-01-27 08:38:10.017	info	(4203) Start javascript script.js.common.Message.Skript_1
`

**Comment by maxpd1** [comment]
Selbes Problem hier. 

Es wird auch trotz grünem Adapter kein "Start" als Systemnachricht gesendet.

**Comment by Diginix** [comment]
Bei mir schon:

> 2022-01-27 08:16:18.120 - info: telegram.0 (405092) starting. Version 1.11.0 in /opt/iobroker/node_modules/iobroker.telegram, node: v14.18.3, js-controller: 3.3.22

**Comment by GermanBluefox** [comment]
Fixed in 1.11.1

**Comment by vepman** [comment]
Leider ist der Fehler in v1.11.0 bei mir immer noch.

**Comment by Diginix** [comment]
Ist ja auch erst mit 1.11.1 gefixt. Musst über die Katze installieren.

**Comment by vepman** [comment]
Alles klar, Danke.
Geht jetzt unter v1.11.1

**Comment by maxpd1** [comment]
> Bei mir schon:
> 
> > 2022-01-27 08:16:18.120 - info: telegram.0 (405092) starting. Version 1.11.0 in /opt/iobroker/node_modules/iobroker.telegram, node: v14.18.3, js-controller: 3.3.22


Ich meinte Versand der  Systemnachricht "start" an den Telegram Channel.
