### ISSUE TITLE
Update 1.11

### ISSUE THREAD

**Issue by Dragon0501** [iobroker-community-adapters/ioBroker.telegram#294]
After Update to 1.11.0 no messages will be delivered.

**Comment by Apollon77** [comment]
use 1.11.1

**Comment by Dragon0501** [comment]
Don't want to update by the cat. Will wait until the update to 1.11.1 is offered, because don't want to corrupt the update function.

**Comment by Apollon77** [comment]
1.11.1 should come to the beta repo soon ...

**Comment by Dragon0501** [comment]
Perfect! Thank you very much!

**Comment by Dragon0501** [comment]
1.11.1 was offered....
