### ISSUE TITLE
Telegram audio from bot to saiyt.

### ISSUE THREAD

**Issue by saykl** [iobroker-community-adapters/ioBroker.telegram#298]
similar functionality is in Google home https://support.google.com/googlenest/answer/7531913
I want to record a voice message in the telegram bot and send it to the driver sayit.

**Comment by GermanBluefox** [comment]
It should be possible with javascript and activated option "Save media files"

**Comment by mcm1957** [comment]
fixed according to @GermanBluefox.
Please drop a note or open a new issue if further problems exist.
