### ISSUE TITLE
Protect Passwords

### ISSUE THREAD

**Issue by svcru** [iobroker-community-adapters/ioBroker.telegram#300]
Area _protectedNative_ contains the password and token parameters, and is protected from being read in scripts. But _passwordRepeat_ is displayed and through it you can find out the password. The proxy server parameters (address, username and password) are also not protected too.
![photo_2022-02-17_09-50-19](https://user-images.githubusercontent.com/7061896/154407556-baeb5f21-b76f-4ef6-abf9-fbb965228a1f.jpg)

Sorry for my English

discussion was here (RU) https://t.me/iobroker/161161

**Comment by Apollon77** [comment]
It seems that there are also some settings missing in io-package at all (like proxy password).

**Comment by Apollon77** [comment]
PasswordRepeat will be removed in next version ... rest open

**Comment by GermanBluefox** [comment]
Fixed in admin
