### ISSUE TITLE
Media File Save - Qualität einstellbar machen

### ISSUE THREAD

**Issue by LastPerfectTobi** [iobroker-community-adapters/ioBroker.telegram#301]
Wenn man einem Bot eine Grafikdatei schickt werden immer 4 Dateien in folgenden Qualitätsstufen abgespeichert:
Low, Med, High, Highdef

```
const qualityMap = {
            0: 'low',
            1: 'med',
            2: 'high',
            3: 'highdef'
        };
```

Lässt sich das einstellbar machen welche Qualitätsstufe man haben will?
Dann würden auch nicht mehr 4 Dateien abgespeichert werden sondern nur noch eine.

**Comment by mcm1957** [comment]
fixed according to @GermanBluefox.
Please drop a note or open a new issue if further problems exist.
