### ISSUE TITLE
Support MarkdownV2 and escape characters correctly

### ISSUE THREAD

**Issue by noffycws** [iobroker-community-adapters/ioBroker.telegram#309]
I use the latest version (1.12.0) of the telegram adapter. I use it with blockly to send messages and different states.

After the new MarkdownV2 I get the followin error messages in the log:
`Error: ETELEGRAM: 400 Bad Request: can't parse entities: Character '|' is reserved and must be escaped with the preceding '\'`

After that I get the entities which should escaped with "\".

I use the following entities where the error occurs:
"|" (pipe)
"." (Punkt)
"-" (dash)

In this case the messages are not send.

When I escape the entities in the blockly script, the messages will be send. But now I have all points in the end of a sentence escaped. And I use the same text parts for the Alexa output which sounds weird.

This error is since the MarkdownV2 is integrated. Before this all worked fine for years.

I don't know if the error occurs in the HTML-markup, too.

Maybe there is an error in escaping the entities directly in the source code of the adapter.

**Comment by Apollon77** [comment]
What is "the new MarkdownV2" ?? More details please

**Comment by noffycws** [comment]
In Blockly I can choose the parsemode. There I can choose "default", "HTML" or "MarkdownV2". In earlier version the was only the parsemode "markdown" (without V2).

**Comment by Apollon77** [comment]
Then please provide a debug log from the usage of this so that I mabe can see more

**Comment by noffycws** [comment]
You see the debug log in my issue description.

Meanwhile I have seen, that's not an error, it's a feature of MarkdownV2:
https://core.telegram.org/bots/api#markdownv2-style

...
In all other places characters '_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!' must be escaped with the preceding character '\'.
...

In Markdown (V1) there must be only the characters '_', '*', '`', '[' has to be escaped.

I think the characters has to be escaped if they have to be display in the message. But it is a little bit strange and maybe other users has the same problem. Parsemode HTML is no option for me. Maybe you can build in a feature in the adapter where some typical characters will be escaped automaticly when sending the message.

Maybe this can be done for this characters which will be usually used within texts:
'+', '-', '=', '|', '.', '!'

Best regards
Michael

**Comment by Apollon77** [comment]
> You see the debug log in my issue description.

??? I see one error line there ... Please send me a Full debug log

**Comment by noffycws** [comment]
I have no more entries in the log. I only have this one error line.

I think it is an error from the Telegram API, because I haven't escaped the characters mentioned on the Telegram API website.

**Comment by Apollon77** [comment]
Did you tried escaping them?

**Comment by noffycws** [comment]
Of course. I wrote it in my last answer. This should be a master change from "markdown" to "MarkdownV2". Maybe other users of the telegram adapter has the same problem.

Maybe the adapter can escape some characters by itself. The differences are described in the link above.

**Comment by PascalBru** [comment]
Having the same problem with **-** which should be escaped.

**Comment by GermanBluefox** [comment]
Blockly has now option to escape the string.
In javascript the strings could be escaped like this 
```
text = text.replace(/([-_*\[\]()~`>#+=|{}.!])/g, "\\$1")
```

**Comment by mcm1957** [comment]
fixed according to @GermanBluefox.
Please drop a note or open a new issue if further problems exist.
