### ISSUE TITLE
If cronjob is disabled, it should stay disabled after update

### ISSUE THREAD

**Issue by thost96** [iobroker-community-adapters/ioBroker.telegram#311]
**Describe the bug**  
I manually removed the cronjob which restarts telegram every night at 05:00 am as this triggers a notification every time and also without that restart telegram is working fine for me. But after an update each time the cronjob is activated again. Please add a check, that if the cronjob has been removed it will not be added after an update again. 

**Versions:**  
 - Adapter version: v1.12.2
 - JS-Controller version: 4.0.21
 - Node version: 14.19.0 
 - Operating system: ubuntu

**Comment by Apollon77** [comment]
Please open this issue in js-controller ... this is a general topic.
