### ISSUE TITLE
Report State Changes is reporting updates not changes

### ISSUE THREAD

**Issue by quotschmacher** [iobroker-community-adapters/ioBroker.telegram#324]
**Describe the bug**  

if activating the "Report changes" function in the states setting, every update is sent. So either this option needs to be renamed, the way it works needs to be corrected, or better: a choice between "Report changes" and "Report Updates" should be implemented.

**Versions:**  
 - Adapter version: v1.13.0
 - JS-Controller version: v4.0.23
 - Node version: v12.22.10
 - Operating system: debian - docker

**Additional context**  
was already addressed in #190

**Comment by GermanBluefox** [comment]
Now you have an option: 
![image](https://user-images.githubusercontent.com/4582016/219602841-5edebca0-4d66-46d9-a3ea-d13b122b2edd.png)

**Comment by mcm1957** [comment]
fixed according to @GermanBluefox.
Please drop a note or open a new issue if further problems exist.
