### ISSUE TITLE
Adapter läuft unter Admin 5 nicht 

### ISSUE THREAD

**Issue by Frank795** [iobroker-community-adapters/ioBroker.telegram#332]
Hallo, ich wollte heute die neue Beta mal testen, nach der Installation wurde im Log gezeigt das Admin 6 laufen muss, bei der installation kam aber kein Hinweis dazu das die  Vorraussetzungen nicht passen.
`startInstance system.adapter.telegram.0 Adapter dependency not fulfilled on any host: required adapter "admin" has wrong version. Installed "5.4.9", required ">=6.1.6"!`
Wenn das so OK ist Issue einfach wieder schließen.

**Comment by Apollon77** [comment]
Wie hast Du die Beta denn installiert? Von GitHub? Dann hast du nicht die Beta sondern die Development Version und da werden die relevanten Checks nicht ausgeführt. Gleiches wenn "von NPM" im Admin ...

Ansonsten hätte es geprüft werden sollen

**Comment by Frank795** [comment]
Nein über den Adabter Tab (oder Info) bin nicht 100% sicher  im IOBroker von Git mache ich nur auf anweisung ;)

**Comment by Apollon77** [comment]
Ja wo nun? Admin sollte es prüfen. Info Tab weiss ich nicht

**Comment by Frank795** [comment]
Gerade nochmal unter Adapter geupdatet, keine meldung wieder Fehler im Log

**Comment by Apollon77** [comment]
Ja dann Admin issue. Vor allem sagen welche Admin version!
