### ISSUE TITLE
State value to set for "telegram.0.communicate.requestUserId" has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by Steff42** [iobroker-community-adapters/ioBroker.telegram#333]
Hallo,
nach Update auf Version V1.14.1 bekomme ich die o.g. Meldung im Log. Wenn die Meldung Auftritt erzeuge ich ein Keyboard in Telegram.

Hier mal die Objektdaten:

`{
  "_id": "telegram.0.communicate.requestUserId",
  "type": "state",
  "common": {
    "role": "text",
    "name": "User ID of last received request",
    "type": "string",
    "read": true,
    "write": false
  },
  "native": {},
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1657007462410
}`

Ändere ich den Typ von string auf number, taucht der Eintrag nicht auf.

Hier die geänderten Obbjektdaten:

`{
  "_id": "telegram.0.communicate.requestUserId",
  "type": "state",
  "common": {
    "role": "text",
    "name": "User ID of last received request",
    "type": "number",
    "read": true,
    "write": false
  },
  "native": {},
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1657007631254
}`

Gruß Steffen

**Comment by mest2** [comment]
Habe auch das Problem.

**Comment by umbm** [comment]
Fehlermeldung besteht noch immer.
Jeder Neustart des Telegram-Adapters ändert den Datenpunkt wieder zu String

**Comment by Apollon77** [comment]
Ja klar besteht SIe noch, Fix ist noch nicht gemerged und released. Geduld bitte

**Comment by spacemishka** [comment]
Den Fehler bekomm ich schon seit längerer Zeit. Wann kommt denn mal der Fix?

**Comment by Apollon77** [comment]
with next update
