### ISSUE TITLE
add information that ADMIN 6 is required

### ISSUE THREAD

**Issue by wendy2702** [iobroker-community-adapters/ioBroker.telegram#358]
Hi,
can you please add a information that Admin 6 is required to get 1.14.1 running.

Regards

**Comment by TDCroPower** [comment]
here the same problem with Admin 5.4.9 and the Telegram 1.14.1 installed, no warning when updating.
The instance no longer works afterwards and only in the log you see a note that you need 6.1.9 or higher....

`startInstance system.adapter.telegram.0 Adapter dependency not fulfilled on any host: required adapter "admin" has wrong version. Installed "5.4.9", required ">=6.1.6"!`

**Comment by Apollon77** [comment]
Pleas emake sure that the admin adapters on ALL hosts have at least the needed version ... not only the current host. And if it is still an issue try "iob upload admin"

**Comment by Apollon77** [comment]
If there are other hosts and older admin versions there then it seems that Admin checks are not correct anymore for globalDependencies

**Comment by Feuer-sturm** [comment]
I can reproduce the issue as well on my test system. I created an admin issue https://github.com/ioBroker/ioBroker.admin/issues/1599 so that Bluefox can check this.
