### ISSUE TITLE
Telegram Fehlermeldung im Log 1 of 1 recipients are unknown!

### ISSUE THREAD

**Issue by marian-t-web-de** [iobroker-community-adapters/ioBroker.telegram#360]
**Describe the bug**  

Telegram Aufruf in JS mit Angabe von User endet seit Version 1.13.0 mit o.g. Fehlermeldung, ohne oder mit Passwort in der iob Instance. 
Die Lösung vom Apollon77 unter "https://forum.iobroker.net/topic/6164/gel%C3%B6st-passwort-bei-telegram/2":
- Gib das Passwort im Adapter an
- Starte den Adapter
- gehe in Telegram und starte einen Chat mit deinem Bot (nicht dem Botfather, sondern deinem angelegten Bot)
- Da brauchst Du dann das Passtwort"

funktioniert bei mir in dem letzten Punkt definitiv nicht. 
Darüber hinaus funktioniert der Aufruf in ioBroker  mit korrektem User nicht, ohne aber doch??
Danach steht in telegram.o.communicate.users statePoint  {"1653738...":{"firstName":"Manni"}} und zwar voher? 

Mit chatId funktioniert es - wenn man die herausfindet. Es ist kein Workaround - ich möchte den User wie bisher selber auswählen können. 

**To Reproduce**  

Telegram Aufruf in JS mit user 
sendTo("telegram.0", "send", {
                                text: "Hallo alle",
                                user: "Manni..._bot"  // Name gekürzt
                        });  // sendTo... 

**Expected behavior**  

Der Aufruf soll wie bisher funktionieren.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <Telegram-1.13.0>

Plattform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
3.75 GB
System-Betriebszeit
16 T. 22:40:18
Node.js
v12.22.8 (Es gibt eine neuere Version: v12.22.12 - Empfohlene Version v16.16.0)
time
1658257198234
timeOffset
-120
Anzahl der Adapter
422
NPM
6.14.15
Datenträgergröße
6.87 GB
freier Festplattenspeicher
1.41 GB
Betriebszeit
10 T. 00:10:08
Aktive Instanzen
18
Weg
/opt/iobroker/
Hostname
raspberrypi

**Additional context**

**Comment by klein0r** [comment]
> user: "Manni..._bot" // Name gekürzt

Du kannst keine Nachrichten mit einem Bot an einen anderen Bot schicken

**Comment by Apollon77** [comment]
Bitte mal Debug log vom Telegram adapter zeigen für so eine message

**Comment by marian-t-web-de** [comment]
Hallo,
Ist das iob log gemeint, siehe Anlage.

Es geht mir darum dass der vorher funktionierender telegram aufruf mit userid seit dem adapter update nicht mehr funktioniert. Es sollte gem. Hinweis vom apollon77 durch Eintragen vom Passwort in der Adaptereinstellungen behoben werden, ist aber bei mir nicht der Fall, auch nachdem ich den chat im telegram gelöscht und neu gestartet hatte. 
Und das egal ob mit oder ohne Passwort.

MfG
Marian T.
Von Samsung Galaxy gesendet.

-----Original Message-----

**Comment by marian-t-web-de** [comment]
Hallo,

vielleicht ist das ein Missverständnis mit dem Telegram User.

Vom BotFather wurde „Manni…bot“ als Username genehmigt (die Punkte stehen für weitere Buchstaben – setze ich die nur hier für die Korrespondenz). 

In Bot Info steht Manni und Benutzername ***@***.***…bot“

Demnach habe ich den Telegramm Aufruf in iob-js bisher wie folgt erfolgreich benutzt:

sendTo("telegram", "send", {
                                text: obj.message,
                                user: "Manni..._bot"  // Name nur hier gekürzt                                 
                        });  // sendTo...

Ab Telegram v1.13.0 funktioniert das nicht mehr, Fehler „1 of 1 recipients are unknown!“

In iob unter Telegram->..->users finde ich die ChatId/firstName

{"1653738...":{"firstName":"Manni"}}

wahrscheinlich weil im Adapter-Instanz „Speichere Nutzer-IDs zur Vermeidung einer erneuten Kennwortabfrage“ (was ist Nutzr-ID?

Was soll nun bei  sendTo user: stehen damit es funktioniert? 

„Manni“, "Manni..._bot" , "Manni..“ (ohne „_bot“ oder auch ***@***.***_bot"  liefern allesamt Fehlermeldungen (User Manni hast not set an username in the Telegram App!! für „Manni“ bzw. 1 of 1 recipients are unknown! für den Rest.

Ich habe das Passwort in iob  gesetzt, wo/wie ist der in Telegram zu setzen? Hat das was mit Anmeldecode in Telegram zu tun? Nach Löschen vom Chat und Neustart kommt keine Passwortabfrage.

Ich könnte ggfs. den Adapter debugegn – ob das was bringt?

Was noch nicht korrekt ist, sendTo ohne user:  geht (ohne Fehler) an den "Manni..._bot"  chat, vllt. wird der iob  SP users von letzten Aufruf verwendet. Ist so gewollt/korrekt?

Was geht, sendTo mit  chatId: '1653738…', nur wie schicke ich dann eine Nachricht an einen weiteren z.B.  User2(_bot) ohne die chatId von ihm zu kennen? In Telegram ist die nicht ausgewiesen.


Viele Grüße
Marian

-----Original Message-----

**Comment by klein0r** [comment]
> Vom BotFather wurde „Manni…bot“ als Username genehmigt (die Punkte stehen für weitere Buchstaben – setze ich die nur hier für die Korrespondenz). In Bot Info steht Manni und Benutzername ***@***.***…bot“
> Ab Telegram v1.13.0 funktioniert das nicht mehr, Fehler „1 of 1 recipients are unknown!“

Genau das ist doch der Punkt. Im Feld "user" gibt man an, an welchen Telegram-Nutzer der Bot die Nachricht schicken soll. Absender ist ja der Bot selbst (über das zugehörige Token).

Im Feld User muss also ein Benutzer angegeben werden, welcher Telegram nutzt. Also Dein Account und **nicht der vom Bot**. Nach deiner Logik würde er ja sonst sich selbst schreiben. Daher ja auch mein Hinweis, dass ein Bot nicht an andere Bots schreiben kann (an sich selbst ergibt ja noch weniger Sinn).

Es kann sein dass die Prüfung neu dazu gekommen ist, aber die Meldung ist in jedem Fall richtig. Also User einfach leer lassen (dann wird an die authentifizierten Nutzer geschrieben) oder eben einen Benutzer von einem Telegram-Nutzer angeben, welcher kein Bot ist.

**Comment by marian-t-web-de** [comment]
Hallo, vielleicht ist das ein Missverständnis mit dem Telegram User. Vom BotFather wurde „Manni…bot“ als Username genehmigt (die Punkte stehen für weitere Buchstaben – setze ich die nur hier für die Korrespondenz).  In Bot Info steht Manni und Benutzername ***@***.***…bot“ Demnach habe ich den Telegramm Aufruf in iob-js bisher wie folgt erfolgreich benutzt:sendTo("telegram", "send", {                                text: obj.message,                                user: "Manni..._bot"  // Name nur hier gekürzt                                                         });  // sendTo... Ab Telegram v1.13.0 funktioniert das nicht mehr, Fehler „1 of 1 recipients are unknown!“ In iob unter Telegram->..->users finde ich die ChatId/firstName {"1653738...":{"firstName":"Manni"}} wahrscheinlich weil im Adapter-Instanz „Speichere Nutzer-IDs zur Vermeidung einer erneuten Kennwortabfrage“gesetzt ist (was ist Nutzer-iD?) Was soll nun bei  sendTo user: stehen damit es funktioniert?  „Manni“, "Manni..._bot" , "Manni..“ (ohne „_bot“ oder auch ***@***.***_bot"  liefern allesamt Fehlermeldungen (User Manni hast not set an username in the Telegram App!! für „Manni“ bzw. 1 of 1 recipients are unknown! für den Rest. Ich habe das Passwort in iob  gesetzt, wo/wie ist der in Telegram zu setzen? Nach Löschen vom Chat und Neustart kommt keine Passwortabfrage.Hat das was mit Anmeldecode in Telegram zu tun? Was noch nicht korrekt ist, sendTo ohne user:  geht (ohne Fehler) an den "Manni..._bot"  chat, vllt. wird der iob  SP users von letzten Aufruf verwendet. Ist so gewollt/korrekt? Was geht, sendTo mit  chatId: '1653738…', nur wie schicke ich dann eine Nachricht an einen weiteren z.B.  User2(_bot) ohne die chatId von ihm zu kennen? Sehe in adapter.js bis auf die obj.chatId / user: "Manni..._bot"  kein Unterschied.  Wo die Fehlermeldung generiert wird finde ich nicht.  MfGMarianGesendet von Mail für Windows 10

**Comment by klein0r** [comment]
Bitte mal ordentliche Kommentare schreiben und nicht auf die Mail antworten. Da sieht ja keiner durch.

**Comment by klein0r** [comment]
Warum liest Du nicht erstmal meinen ausführlichen Kommentar?

- Du hast einen Telegram Nutzer. Wenn Du anderen etwas mit der App schreibst, dann sehen die ja deinen Nutzernamen usw.
- Diesen kann man in den Einstellungen der Telegram-App ansehen
- Falls kein Benutzername vergeben ist, dann kann man das über die App nachholen
- DIESER Benutzername muss bei user übergeben werden. Nix mit Bot. Nie. Das geht wie 3x geschrieben nicht.
- Dass es vorher funktioniert hat war so nicht vorgesehen, weil man noch nie Nachrichten an Bots schreiben konnte

Für mehr Hilfestellung bitte ein komplettes Log auf Debug-Level liefern. Sonst kann man hier nur raten was gerade konfiguriert ist.
