### ISSUE TITLE
Error when using parse mode MarkdownV2

### ISSUE THREAD

**Issue by Standarduser** [iobroker-community-adapters/ioBroker.telegram#379]
When using sentTo function for telegram with parse mode `MarkdownV2` and texts containing `.` the message isn't sent.
The log file shows following error message:

```
2022-08-14 12:56:03.782 | error | Cannot send message [chatId - xxxxxxxxx]: Error: ETELEGRAM: 400 Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
```

May it be possible to integrate a check box for auto-escape the following chars?
```
'_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!'
```

**Comment by l4rs** [comment]
Same issue here, especially with Blocklys that originally used Markdown instead of the newer Markdown_V2. It took me some time to even find and solve it.

A checkbox, as suggested by @Standarduser, will not work in my opinion, because the desired formatting would then also be escaped.

I used a small js function for now:
```
return text
   .replace(/\_/g, '\\_')
   .replace(/\*/g, '\\*')
   .replace(/\[/g, '\\[')
   .replace(/\]/g, '\\]')
   .replace(/\(/g, '\\(')
   .replace(/\)/g, '\\)')
   .replace(/\~/g, '\\~')
   .replace(/\`/g, '\\`')
   .replace(/\>/g, '\\>')
   .replace(/\#/g, '\\#')
   .replace(/\+/g, '\\+')
   .replace(/\-/g, '\\-')
   .replace(/\=/g, '\\=')
   .replace(/\|/g, '\\|')
   .replace(/\{/g, '\\{')
   .replace(/\}/g, '\\}')
   .replace(/\./g, '\\.')
   .replace(/\!/g, '\\!');
```

and I wish there was a Blockly tag for that - what do you all mean?

**Comment by GermanBluefox** [comment]
Added escape option:
![image](https://user-images.githubusercontent.com/4582016/219586165-1631b773-0cfc-47de-b73d-331401ca3449.png)

If someone has a good translation of "escape chars" into german, I will appreciate it. (PR is better)

**Comment by Standarduser** [comment]
"Escapezeichen verwenden" or "Escapezeichen setzen"

Sorry, not able to send a PR at the moment

**Comment by GermanBluefox** [comment]
> I would suggest to not escape formatting chars, because that would prevent users to make text italic or bold

From discussion I understand that in MarkdownV2 required it: https://core.telegram.org/bots/api#markdownv2-style
And it is configurable, so the user can prepare text himself as it needed.

**Comment by Standarduser** [comment]
You are right. When I opened this issue I did not notice that escaping all chars would prevent formatting of text.
I think ` * _ ~ | ` should not be escaped if they appear between char 1 and 126.

Maybe the best solution would be to make it configurable in instance settings?
