### ISSUE TITLE
Option / Setting to disable "Restarting..." and "Started!" message

### ISSUE THREAD

**Issue by MediaMemphis** [iobroker-community-adapters/ioBroker.telegram#407]
**Is your feature request related to a problem? Please describe.**
There is no need for me, to get every restart information of the ioBroker / "ioBroker.telegram" -Adapter and / or to disturb the user(s) every time if something happen.

**Describe the solution you'd like**
I'd like to have an option, which disables the default messages: "Restarting..." and "Started!" by restarting the adapter.

**Comment by Apollon77** [comment]
Why you not simply increase the loglevel to warn.. Then you do not get info logs anymore and you're fine?

**Comment by MediaMemphis** [comment]
Hi, this does not have any effect. 
I'll receive every morning the same Message, sent by telegram bot.

**Comment by peterfido** [comment]
Die Startmeldungen würde ich auch gern deaktivieren können. Wenn man nachts am System bastelt, weckt man sonst die Frau.

**Comment by mcm1957** [comment]
> Why you not simply increase the loglevel to warn.. Then you do not get info logs anymore and you're fine?

Ich galb da gehts nicht um Meldungen im (ioBroker)-Log sindern um die restartung / started Meldungen in Telegram. Die werden wohl kaum vom ioBroker Log Level abhängen

**Comment by mcm1957** [comment]
As far as I known - and as I just tested with v1.14.1 - you do not receive any restart / started messages if the text files "restarting" and/or "restarted" are EMPTY (see screenshot)

![Screenshot 2022-10-26 101200](https://user-images.githubusercontent.com/28575778/197971390-eb911337-fc87-49c8-b880-8fdfdd7b07a0.png)

Please note that admin does not display an empty area for empty text fields but shows the lebale of the textfield instead. So the captured screenshot sown emptye (blank) data.

And please note too, that after saving the blank data the adapter restarts. This sends one (last) message as the new config will be in use only AFTER the restart so the shutdown still uses the old config.

**Comment by mcm1957** [comment]
@[MediaMemphis](https://github.com/MediaMemphis)
@[peterfido](https://github.com/peterfido)

Please verify

**Comment by MediaMemphis** [comment]
> @[MediaMemphis](https://github.com/MediaMemphis) @[peterfido](https://github.com/peterfido)
> 
> Please verify

Hi @mcm1957, thank you for your support! Yes, this helped to disable these messages. 
There was an _ in the textbox, maybe that's why I didn't understand to change the vlaue :/.

**Comment by Apollon77** [comment]
We should document it

**Comment by mcm1957** [comment]
Its already documented at the help text in wblate.
We "only" must check why its not delivered....

See oth issue regarding helptest missing

**Comment by mcm1957** [comment]
Documentation is likely available at next release v1.15.x

The help text below the two textfields describes that an empty field suppresses the telegram messages:
"This text will be sent to clients once the adapter instance started. Leave blank to deactivate."

**Comment by mcm1957** [comment]
The help text shown with 1.15.2 decribes the functionality, i.e. 
```
DE: Dieser Text wird nach dem Start der Adapter-Instanz an die Clients gesendet. Zum Deaktivieren: leer lassen.
EN: This text will be sent to clients once the adapter instance is going to be stopped. Leave blank to deactivate.
```

If additional documentation should be implemented this issue should be kept open, otherwise it could be closed in my oppinion

**Comment by peterfido** [comment]
Sorry für die späte Rückmeldung. Leer lassen hilft. Ich war nur irritiert, dass dort beim leer lassen die Standard Texte scheinbar gesetzt sind.

**Comment by mcm1957** [comment]
> Sorry für die späte Rückmeldung. Leer lassen hilft. Ich war nur irritiert, dass dort beim leer lassen die Standard Texte scheinbar gesetzt sind.

Versteh ich :-)
Ist aber das Standard Google Design / Verhalten für Textfelder. Daher keine Änderung geplant.
