### ISSUE TITLE
Suspect messages shown in chrome console

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.telegram#408]
**Describe the bug**  
While searching for a problem with JS Rules I noticed the following messages output at chrome console:

```
[2022-09-28T06:13:27.888Z] Try to connect
BlocklyEditor.jsx:115                                                Detected custom blockly: telegram
:8081/adapter/telegram/rules/i18n/en.json:1         Failed to load resource: the server responded with a status of 404 (Not Found)
index.jsx:141                                                            Cannot load i18n "http://localhost:8081/adapter/telegram/rules/i18n/en.json": SyntaxError: Unexpected token 'F', "File rules"... is not valid JSON
:8081/adapter/telegram/rules/customRuleBlocks.js:1  Failed to load resource: the server responded with a status of 404 (Not Found)
```

I'm not sure whether they are "normal" expected behavior or not but I think they should be checked.

**I could NOT detect any malfunction of the adapter yet**

**Versions:**  
 - Adapter version: Telegram 1.14.1, Admin 6.2.22, JS 6.0.3
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: Linux pi4 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux

**Comment by mcm1957** [comment]
verified by @Apollon77

**Comment by mcm1957** [comment]
I attach chrome log if someone wants to check it in detail

[10.17.2.20-1664351653690.log](https://github.com/iobroker-community-adapters/ioBroker.telegram/files/9662910/10.17.2.20-1664351653690.log)

**Comment by GermanBluefox** [comment]
Telegram does not installed, but block for that is used. `iob u telegram` could help

**Comment by mcm1957** [comment]
I do not fully understand your question.
If you mean, that I should install telegram adapter too, I can tell you that it was installed.

I think these messages are / where related to https://github.com/ioBroker/ioBroker.javascript/issues/1148. As far as I know and discussed with @Apollon there is (or was) a problem, that telegram defined rules support but did not provide the required files.  I do not know, whther this has been fixed in the meantime.

**Comment by mcm1957** [comment]
not yet solved

**Comment by mcm1957** [comment]
seems to be really outdated.
