### ISSUE TITLE
Enhancy by easy Telegram Bot

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.telegram#48]
Idee eines einfach zu konfigurierendem Telegram Bots.
Kein Javascript mehr für jede Funktion sondern ein GUI ähnlich Blockly

Man wählt ein Objekt aus definiert was der Bot damit tun soll und gibt die Ausgabe an den User an.

Man kann sich mit Telegram einen kleinen Bot basteln der bei einem Keyword oder Command entweder die passende Ausgabe ausgibt oder eine Auswahl anbietet.

https://core.telegram.org/bots/2-0-intro

Ich habe mit ein JS gebaut das bei dem Triggerwort Temperatur eine Auswahl der verfügbaren Temperaturmesser zeigt die man dann per Button anklicken kann. Dann bekomme ich die Temperatur.

Es geht alles über Blockly oder JS ist aber für mich zumindest kompliziert wenn es komplexer wird.

Übernommen von https://github.com/ioBroker/AdapterRequests/issues/19

**Comment by GermanBluefox** [comment]
The user can define if the state should be shown in the chat by writing "/cmds". 
"/cmds" could be replaced on any text e.g. "?"
![image](https://user-images.githubusercontent.com/4582016/80205473-f2e40680-862a-11ea-94b4-b5220c53fb67.png)
![image](https://user-images.githubusercontent.com/4582016/80205760-77cf2000-862b-11ea-8688-f8d18109d30c.png)
