### ISSUE TITLE
Driverv don't work after update js-controller: 4.0.23->4.0.24

### ISSUE THREAD

**Issue by 2scorpio** [iobroker-community-adapters/ioBroker.telegram#495]
Hello.
Driverv don't work after update js-controller: 4.0.23->4.0.24

`<html>
<body>

telegram.0 | 2023-01-16 19:16:39.298 | error | getMe (reconnect #10) Error:Error: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
-- | -- | -- | --
telegram.0 | 2023-01-16 19:14:49.106 | error | getMe (reconnect #0) Error:Error: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
telegram.0 | 2023-01-16 19:14:39.085 | error | getMe Error:Error: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
telegram.0 | 2023-01-16 19:14:29.086 | error | setWebHook Error:Error: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org
telegram.0 | 2023-01-16 19:14:19.028 | debug | Start polling with: 300(number) ms interval
telegram.0 | 2023-01-16 19:14:18.807 | debug | Schedule restart: * */12 * * *
telegram.0 | 2023-01-16 19:14:18.759 | info | starting. Version 1.15.2 in /opt/iobroker/node_modules/iobroker.telegram, node: v14.21.2, js-controller: 4.0.24
telegram.0 | 2023-01-16 19:14:18.473 | debug | Plugin sentry Initialize Plugin (enabled=true)
telegram.0 | 2023-01-16 19:14:11.775 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
telegram.0 | 2023-01-16 19:14:11.774 | debug | Plugin sentry destroyed
telegram.0 | 2023-01-16 19:14:11.773 | info | terminating
telegram.0 | 2023-01-16 19:14:11.271 | info | Got terminate signal TERMINATE_YOURSELF
telegram.0 | 2023-01-16 19:14:10.769 | error | getMe (reconnect #0) Error:Error: EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org

</body>
</html>`

**Comment by Apollon77** [comment]
Thiserror has nothing to do with the js-controller upgrade normally ... The error means that there is a DNS issue with resolving the given domainnname!

Error: getaddrinfo EAI_AGAIN api.telegram.org

Please check your DNS

**Comment by 2scorpio** [comment]
I execte ping on a iobroker server

```
ping api.telegram.org
PING api.telegram.org (149.154.167.220) 56(84) bytes of data.
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=1 ttl=55 time=67.6 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=2 ttl=55 time=73.3 ms

```

**Comment by Apollon77** [comment]
I can only state what the error message is about ... it means that the nodejs process was not able to lookup the IP for the domainname
