### ISSUE TITLE
Configuration of the timeout for questions is missing

### ISSUE THREAD

**Issue by Nogger82** [iobroker-community-adapters/ioBroker.telegram#526]
**Describe the bug**  
There is no option to configure the timeout for a question.

**Expected behavior**  
A way to configure the timeout as described in the readme.

**Versions:**  
 - Adapter version: v1.15.2
 - JS-Controller version: 4.0.24
 - Node version: v16.17.0
 - Operating system: Raspberrypi 4

Thanks for your Support.

**Comment by mcm1957** [comment]
Feature request?

**Comment by tipp88** [comment]
Could this please be added to a release? 
I would love to increase the timeout for callback questions. I just realized that this is not working in current version.
