### ISSUE TITLE
Add /search predefined command to search for state-ids and names and maybe smartdevice-names?!

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.telegram#56]
Allow the search for states using partial ids, ids with wildcards and names.

How to make sure not to return hunderts of ids? :-)

Maybe also allow to use SMartnames to search/Access states?

**Comment by Hypnos3** [comment]
Should this t´really be part of the telegram adapter?

My consern is that this is may be a security issue. So this must be in config and should be disabled by default.

For example I have my own Javascript in place which is doing this, but only for some users. So my telegram using different users and I don't wan't that all users have the posibility to list all states/devices/.... Per type of users the user are able to use this functionality and may see only some of the states/devices/.... Some users are also only in an guest mode where they not allowed to list anything at all.

**Comment by Apollon77** [comment]
Good point. Then also  the already existing /state should be configurable (for security reasons)
