### ISSUE TITLE
Video__note data are not saved - Enhancment

### ISSUE THREAD

**Issue by mcuiobroker** [iobroker-community-adapters/ioBroker.telegram#564]
msg.video_note seems to be the video, which are sending if you press the video-Button in the telegram App and not using the File-Button to get it from your gallery.

![image](https://user-images.githubusercontent.com/84818934/233869978-f3a0c4a0-0a36-48e2-ae6c-289bda0c9f5d.png)

Thank you.

**Comment by mcm1957** [comment]
Please add the minimum version info your issue is related to:
adapter version:
js-controller version:
node:
npm:
OS:

**Comment by mcuiobroker** [comment]
Js Controller 4.0.24
node v18 last
npm: 9.xx

**Comment by mcuiobroker** [comment]
@mcm1957 

Zeile 1041  
} else if (adapter.config.saveFiles && msg.video) {

change to  

} else if (adapter.config.saveFiles && msg.video_note) {

Zeile 1045
saveFile(msg.video.file_id, `/video/${date}.mp4`, res => {

change to 

saveFile(msg.video_note.file_id, `/video/${date}.mp4`, res => {
