### ISSUE TITLE
cant upgrade to version 1.16.0

### ISSUE THREAD

**Issue by bicmac** [iobroker-community-adapters/ioBroker.telegram#596]
the upgrade end with error output during installation:

`$ iobroker upgrade telegram@1.16.0 --debug

Update telegram from @1.15.6 to @1.16.0

NPM version: 8.19.3

Installing iobroker.telegram@1.16.0... (System call)

npm ERR! code ENOTEMPTYnpm ERR! syscall renamenpm ERR! path /opt/iobroker/node_modules/iobroker.telegramnpm ERR! dest /opt/iobroker/node_modules/.iobroker.telegram-qJ3kkwRAnpm ERR! errno -39

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-06-23T09_35_08_553Z-debug-0.log

host.iobroker Cannot install iobroker.telegram@1.16.0: 217

ERROR: Process exited with code 25`

Here the logfile:

`0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.19.3
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.19.3
2 info using node@v16.19.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 12ms
6 timing config:load:builtin Completed in 12ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/opt/iobroker/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/iobroker/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 21ms
19 timing npm:load:configload Completed in 21ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install iobroker.telegram@1.16.0
23 verbose argv "install" "--save-exact" "iobroker.telegram@1.16.0"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 3ms
27 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs
28 verbose logfile /home/iobroker/.npm/_logs/2023-06-23T09_28_15_146Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 31ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 2 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 1263ms
37 timing idealTree:userRequests Completed in 13ms
38 silly idealTree buildDeps
39 silly fetch manifest iobroker.telegram@1.16.0
40 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules/iobroker.discovery
41 http fetch GET 200 https://registry.npmjs.org/iobroker.telegram 2352ms (cache revalidated)
42 silly placeDep ROOT iobroker.telegram@1.16.0 REPLACE for: iobroker.inst@2.0.3 want: 1.16.0
43 timing idealTree:#root Completed in 2365ms
44 timing idealTree:node_modules/iobroker.telegram Completed in 0ms
45 timing idealTree:buildDeps Completed in 2367ms
46 timing idealTree:fixDepFlags Completed in 14ms
47 timing idealTree Completed in 3676ms
48 timing reify:loadTrees Completed in 3676ms
49 timing reify:diffTrees Completed in 30ms
50 silly reify mark retired [ '/opt/iobroker/node_modules/iobroker.telegram' ]
51 silly reify moves {
51 silly reify   '/opt/iobroker/node_modules/iobroker.telegram': '/opt/iobroker/node_modules/.iobroker.telegram-qJ3kkwRA'
51 silly reify }
52 timing reify:rollback:retireShallow Completed in 0ms`

**Comment by Apollon77** [comment]
Please execute "iob fix" and try again
