### ISSUE TITLE
Please fix issues reported by Adapterchecker

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.telegram#609]
[E516] "rules/customRuleBlocks.js" not found, but JavaScript-Rules support is declared

**Comment by mcm1957** [comment]
@Apollon7**7 

[E516] "rules/customRuleBlocks.js" not found, but JavaScript-Rules support is declared**

Please check what to do and who can fix this as telegram is used by many users

**Comment by foxriver76** [comment]
https://github.com/iobroker-community-adapters/ioBroker.telegram/blob/8dd704f7f5a02e57eb65be4aba78d5be642bc9a3/io-package.json#L180

**Comment by mcm1957** [comment]
Den block einfach entfernen?
Versteh ich das richtig?

**Comment by foxriver76** [comment]
Ich kenne die Funktionalität nicht aber laut der Meldung wird der Block deklariert und ist code wise nicht da.

**Comment by foxriver76** [comment]
Am besten weiß es @GermanBluefox villt kennt @Apollon77 das auch

**Comment by mcm1957** [comment]
According to @Apollon77 everything is fine with code, the checker reports a false positive.
