### ISSUE TITLE
getMe (reconnect #1270) Error

### ISSUE THREAD

**Issue by brian-lagerman** [iobroker-community-adapters/ioBroker.telegram#630]
We're getting a parsing error on each poll, which is receiving an HTML response:
```
getMe (reconnect #1270) Error:Error: EPARSE: Error parsing response: <html> <head><title>302 Found</title></head> <body> <center><h1>302 Found</h1></center> <hr><center>nginx/1.18.0</center> </body> </html>
```

Really not sure where the problem lies...

**Versions:**  
 - Adapter version: 1.16.0
 - JS-Controller version: 4.0.24
 - Node version: v20.5.0
 - Operating system: linux (x64)

**Comment by Apollon77** [comment]
Seems like the Telegram webserver had issue s... problem still there or gone?

**Comment by brian-lagerman** [comment]
Just fired up the adapter again, looks like the problem remains...

**Comment by Apollon77** [comment]
try nodejs 20.6 ... there was a bug in node.js that errored strangely on some http communications

**Comment by Rolf400** [comment]
Any update on this? I'm running nodejs 20.7 and have the same issue

**Comment by Chris25122** [comment]
Same problem here since today

Versions:

Adapter version: 1.16.0
JS-Controller version: 5.0.12
Node version: v18.17.1
Operating system: linux (x64)

**Comment by mcm1957** [comment]
@Please recheck with current release (3.3.2)

**Comment by klein0r** [comment]
Not reproducible with adapter version 3.5.3 and node 20.14.0
