### ISSUE TITLE
Bild senden aus dem iobroker Storage

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.telegram#678]
es ist nicht möglich Bilder aus dem iobroker Storage zu versenden 
![grafik](https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/6681528/af7bc1a1-3cee-4846-a3bd-1b9c4aa3639d)

@Apollon77  Zitat 
muss man mal überlegen wie man das so baut das es auch der Filestore sein kann ... am besten eine methode die ein /0_userdata.0/pvforecast.jpg erkennt (regex auf ersten part das es ein instanz-string ist) und dann auch im iobroker Store schaut und von dort nimmt ... aber vermutlich entweder file temporär cached bzw man muss schauen was die bot api macht

**Comment by klein0r** [comment]
Related to https://github.com/ioBroker/ioBroker.js-controller/issues/2710

Workaround: https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#createtempfile

```js
readFile('0_userdata.0', 'test.jpg', (err, data, mimeType) => {
    if (err) {
        console.error(err);
    } else {
        const tempFilePath = createTempFile('test.jpg', data);

        // Use the new path in other scripts (e.g. sendTo)
        sendTo('telegram', 'send', {
            text: tempFilePath,
            user: 'yourUsername',
        });
    }
});
```
