### ISSUE TITLE
sendTo gives strange return value

### ISSUE THREAD

**Issue by arniworx** [iobroker-community-adapters/ioBroker.telegram#679]
hi!
since version 2.0.0 i get strange response from the telegram adapter
a simple call:
sendTo('telegram.0',  {text: 'Test message'}, function (res) {
    console.log(res);
});

gives me:
{"316433688":98885}0

can someone explain, what's going on?
br
-arni

**Comment by mcm1957** [comment]
See README.md V2.0.0 last line reference::
https://github.com/iobroker-community-adapters/ioBroker.telegram/blob/master/README.md#200-2023-10-09

and for technical reference:
https://github.com/iobroker-community-adapters/ioBroker.telegram/pull/652

**Comment by arniworx** [comment]
ok, thanks, expected something like that.
what's with the trailing "0"?

**Comment by mcm1957** [comment]
@boergegrunicke
@GermanBluefox 

Can someone of you answer this question plesse?

**Comment by mcm1957** [comment]
Thanks.
Please feel free to mention me if a quick merge / fix should becapplied
