### ISSUE TITLE
Error mit  Telegram Server mode und SSL

### ISSUE THREAD

**Issue by vr6syncro** [iobroker-community-adapters/ioBroker.telegram#70]
`

host.ioBroker | 2018-09-13 20:36:06.678 | error | instance system.adapter.telegram.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at WritableState.onwrite (_stream_writable.js:90:5)
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at onwrite (_stream_writable.js:378:7)
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at afterWrite (_stream_writable.js:387:3)
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/PerMessageDeflate.js:249:5
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/Receiver.js:368:7
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/Receiver.js:536:18
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at Receiver.ontext (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/WebSocket.js:841:10)
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at WebSocket.emit (events.js:191:7)
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at emitTwo (events.js:106:13)
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at WebSocket.onMessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/WebSocket.js:442:14)
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at WebSocket.ws.onmessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transports/websocket.js:146:10)
Caught | 2018-09-13 20:36:06.678 | error | by controller[8]: at WS.Transport.onData (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:137:8)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at WS.Transport.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:145:8)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at WS.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at WS.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:268:10)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Socket.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:451:14)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Socket.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:322:16)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2018-09-13 20:36:06.677 | error | by controller[8]: at Socket.that.getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:724:21)
Caught | 2018-09-13 20:36:06.676 | error | by controller[8]: at /opt/iobroker/node_modules/iobroker.telegram/main.js:65:32
Caught | 2018-09-13 20:36:06.676 | error | by controller[8]: at Object.createServer (/opt/iobroker/node_modules/iobroker.js-controller/lib/letsencrypt.js:55:26)
Caught | 2018-09-13 20:36:06.676 | error | by controller[8]: at Object.Greenlock.create (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/greenlock/index.js:258:13)
Caught | 2018-09-13 20:36:06.676 | error | by controller[8]: at promisifyAllSelf (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/greenlock/index.js:15:20)
Caught | 2018-09-13 20:36:06.676 | error | by controller[8]: at Array.forEach (native)
Caught | 2018-09-13 20:36:06.676 | error | by controller[8]: at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/greenlock/index.js:17:33
Caught | 2018-09-13 20:36:06.676 | error | by controller[8]: TypeError: util.promisify is not a function
Caught | 2018-09-13 20:36:06.676 | error | by controller[7]: Detected Let's Encrypt v02 URL. Changing version to draft-12.
Caught | 2018-09-13 20:36:06.676 | error | by controller[5]: This will be required in versions v2.3+
Caught | 2018-09-13 20:36:06.676 | error | by controller[5]: (also 'npm install --save le-acme-core' as this legacy dependency will soon be removed)
Caught | 2018-09-13 20:36:06.676 | error | by controller[4]: 'v01' for Let's Encrypt v1 (deprecated)
Caught | 2018-09-13 20:36:06.676 | error | by controller[3]: or
Caught | 2018-09-13 20:36:06.675 | error | by controller[3]: ('v02' is an alias of 'draft-12'
Caught | 2018-09-13 20:36:06.675 | error | by controller[2]: 'draft-12' for Let's Encrypt v2 and ACME draft 12
Caught | 2018-09-13 20:36:06.675 | error | by controller[2]: Please specify 'version' option:
Caught | 2018-09-13 20:36:06.674 | error | by controller[2]: ==========================================================
Caught | 2018-09-13 20:36:06.674 | error | by controller[2]: == greenlock.js (v2.2.0+) ==
Caught | 2018-09-13 20:36:06.674 | error | by controller[2]: ==========================================================
Caught | 2018-09-13 20:36:06.674 | error | by controller[0]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:577:32
Caught | 2018-09-13 20:36:06.674 | error | by controller[0]: In the future, you will have to enable it yourself.
Caught | 2018-09-13 20:36:06.674 | error | by controller[0]: Thu, 13 Sep 2018 18:36:05 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.

`

**Comment by BuZZy1337** [comment]
@GermanBluefox 
... 
by controller[8]: at /opt/iobroker/node_modules/**iobroker.js-controller**/node_modules/greenlock/index.js:17:33
?

**Comment by vr6syncro** [comment]
Das Problem tritt tatsächlich erst mit js Controller 1.5 auf. Ssl haken raus und Fehler ist weg

**Comment by vr6syncro** [comment]
Nach update auf 1.5.2 startet Telegram mit SSL immer noch nicht

`

host.ioBroker | 2018-09-15 15:56:46.879 | error | instance system.adapter.telegram.0 terminated with code 0 (OK)
-- | -- | -- | --
host.ioBroker | 2018-09-15 15:56:46.879 | error | Caught by controller[1]: at WritableState.onwrite (_stream_writable.js:90:5)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at onwrite (_stream_writable.js:378:7)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at afterWrite (_stream_writable.js:387:3)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/PerMessageDeflate.js:249:5
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/Receiver.js:368:7
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/Receiver.js:536:18
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at Receiver.ontext (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/WebSocket.js:841:10)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at WebSocket.emit (events.js:191:7)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at emitTwo (events.js:106:13)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at WebSocket.onMessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/WebSocket.js:442:14)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at WebSocket.ws.onmessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transports/websocket.js:146:10)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at WS.Transport.onData (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:137:8)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at WS.Transport.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:145:8)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at WS.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at WS.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:268:10)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at Socket.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/socket.js:451:14)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at Socket.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:322:16)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
host.ioBroker | 2018-09-15 15:56:46.878 | error | Caught by controller[1]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Socket.that.getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:724:21)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.telegram/main.js:65:32
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Object.createServer (/opt/iobroker/node_modules/iobroker.js-controller/lib/letsencrypt.js:55:26)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at Object.Greenlock.create (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/greenlock/index.js:258:13)
host.ioBroker | 2018-09-15 15:56:46.877 | error | Caught by controller[1]: at promisifyAllSelf (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/greenlock/index.js:15:20)
host.ioBroker | 2018-09-15 15:56:46.876 | error | Caught by controller[1]: at Array.forEach (native)
host.ioBroker | 2018-09-15 15:56:46.876 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/greenlock/index.js:17:33
host.ioBroker | 2018-09-15 15:56:46.876 | error | Caught by controller[1]: TypeError: util.promisify is not a function
host.ioBroker | 2018-09-15 15:56:46.876 | error | Caught by controller[0]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:577:32
host.ioBroker | 2018-09-15 15:56:46.876 | error | Caught by controller[0]: In the future, you will have to enable it yourself.
host.ioBroker | 2018-09-15 15:56:46.876 | error | Caught by controller[0]: Sat, 15 Sep 2018 13:56:46 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
telegram.0 | 2018-09-15 15:56:46.356 | error | TypeError: util.promisify is not a function at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/greenlock/index.js:17:33 at Array.forEach (native) at promisifyAllSelf (/opt/i
telegram.0 | 2018-09-15 15:56:46.355 | error | uncaught exception: util.promisify is not a function

`

**Comment by GermanBluefox** [comment]
Node.js version?

**Comment by vr6syncro** [comment]
6.14.3
und npm 3.10.10

**Comment by GermanBluefox** [comment]
>ist auch bei 1.5.3 nicht weg das hatte ich gerade installiert

Und auch neu gestartet?

**Comment by vr6syncro** [comment]
Ja habe jetzt nochmal frisch neu gestartet aber der Fehler bleibt

**Comment by algar42** [comment]
Several days ago telegram stopped working with the following in the log (connection using socksv5 proxy): 
`

host.server | 2018-09-19 09:31:16.978 | error | instance system.adapter.telegram.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: at TCP.onread (net.js:601:20) code: 'ECONNREFUSED' }
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: at Socket.Readable.push (_stream_readable.js:208:10)
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: at readableAddChunk (_stream_readable.js:250:11)
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: at addChunk (_stream_readable.js:263:12)
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: at Socket.emit (events.js:211:7)
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: at emitOne (events.js:116:13)
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: at Socket.Parser.__onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:33:10)
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: at Parser._onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:122:21)
Caught | 2018-09-19 09:31:16.977 | error | by controller[3]: { Error: connection refused
Caught | 2018-09-19 09:31:16.977 | error | by controller[2]: at TCP.onread (net.js:601:20) code: 'ECONNREFUSED' }
Caught | 2018-09-19 09:31:16.977 | error | by controller[2]: at Socket.Readable.push (_stream_readable.js:208:10)
Caught | 2018-09-19 09:31:16.977 | error | by controller[2]: at readableAddChunk (_stream_readable.js:250:11)
Caught | 2018-09-19 09:31:16.977 | error | by controller[2]: at addChunk (_stream_readable.js:263:12)
Caught | 2018-09-19 09:31:16.976 | error | by controller[2]: at Socket.emit (events.js:211:7)
Caught | 2018-09-19 09:31:16.976 | error | by controller[2]: at emitOne (events.js:116:13)
Caught | 2018-09-19 09:31:16.976 | error | by controller[2]: at Socket.Parser.__onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:33:10)
Caught | 2018-09-19 09:31:16.976 | error | by controller[2]: at Parser._onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:122:21)
Caught | 2018-09-19 09:31:16.976 | error | by controller[2]: { Error: connection refused
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: at TCP.onread (net.js:601:20) code: 'ECONNREFUSED' }
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: at Socket.Readable.push (_stream_readable.js:208:10)
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: at readableAddChunk (_stream_readable.js:250:11)
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: at addChunk (_stream_readable.js:263:12)
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: at Socket.emit (events.js:211:7)
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: at emitOne (events.js:116:13)
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: at Socket.Parser.__onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:33:10)
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: at Parser._onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:122:21)
Caught | 2018-09-19 09:31:16.976 | error | by controller[1]: { Error: connection refused
Caught | 2018-09-19 09:31:16.975 | error | by controller[0]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:653:30
Caught | 2018-09-19 09:31:16.975 | error | by controller[0]: In the future, you will have to enable it yourself.
Caught | 2018-09-19 09:31:16.975 | error | by controller[0]: Wed, 19 Sep 2018 06:31:15 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
telegram.0 | 2018-09-19 09:31:16.961 | info | terminating
telegram.0 | 2018-09-19 09:31:16.460 | error | at TCP.onread (net.js:601:20)
telegram.0 | 2018-09-19 09:31:16.460 | error | at Socket.Readable.push (_stream_readable.js:208:10)
telegram.0 | 2018-09-19 09:31:16.460 | error | at readableAddChunk (_stream_readable.js:250:11)
telegram.0 | 2018-09-19 09:31:16.460 | error | at addChunk (_stream_readable.js:263:12)
telegram.0 | 2018-09-19 09:31:16.460 | error | at Socket.emit (events.js:211:7)
telegram.0 | 2018-09-19 09:31:16.460 | error | at emitOne (events.js:116:13)
telegram.0 | 2018-09-19 09:31:16.460 | error | at Socket.Parser.__onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:33:10)
telegram.0 | 2018-09-19 09:31:16.460 | error | at Parser._onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:122:21)
telegram.0 | 2018-09-19 09:31:16.460 | error | Error: connection refused
telegram.0 | 2018-09-19 09:31:16.459 | error | uncaught exception: connection refused
telegram.0 | 2018-09-19 09:31:16.458 | error | at TCP.onread (net.js:601:20)
telegram.0 | 2018-09-19 09:31:16.458 | error | at Socket.Readable.push (_stream_readable.js:208:10)
telegram.0 | 2018-09-19 09:31:16.458 | error | at readableAddChunk (_stream_readable.js:250:11)
telegram.0 | 2018-09-19 09:31:16.458 | error | at addChunk (_stream_readable.js:263:12)
telegram.0 | 2018-09-19 09:31:16.458 | error | at Socket.emit (events.js:211:7)
telegram.0 | 2018-09-19 09:31:16.458 | error | at emitOne (events.js:116:13)
telegram.0 | 2018-09-19 09:31:16.458 | error | at Socket.Parser.__onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:33:10)
telegram.0 | 2018-09-19 09:31:16.458 | error | at Parser._onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:122:21)
telegram.0 | 2018-09-19 09:31:16.458 | error | Error: connection refused
telegram.0 | 2018-09-19 09:31:16.458 | error | uncaught exception: connection refused
telegram.0 | 2018-09-19 09:31:16.454 | error | at TCP.onread (net.js:601:20)
telegram.0 | 2018-09-19 09:31:16.454 | error | at Socket.Readable.push (_stream_readable.js:208:10)
telegram.0 | 2018-09-19 09:31:16.454 | error | at readableAddChunk (_stream_readable.js:250:11)
telegram.0 | 2018-09-19 09:31:16.454 | error | at addChunk (_stream_readable.js:263:12)
telegram.0 | 2018-09-19 09:31:16.454 | error | at Socket.emit (events.js:211:7)
telegram.0 | 2018-09-19 09:31:16.454 | error | at emitOne (events.js:116:13)
telegram.0 | 2018-09-19 09:31:16.454 | error | at Socket.Parser.__onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:33:10)
telegram.0 | 2018-09-19 09:31:16.454 | error | at Parser._onData (/opt/iobroker/node_modules/socksv5/lib/client.parser.js:122:21)
telegram.0 | 2018-09-19 09:31:16.454 | error | Error: connection refused
telegram.0 | 2018-09-19 09:31:16.454 | error | uncaught exception: connection refused

`
the same connection works fine from phone in the same network. 
Current js-controller version is 1.5.3, but downgrade to 1.4.2 did not solve the problem. 
npm version is 6.2.0, node.js version is 8.12.0

**Comment by BuZZy1337** [comment]
Is this Problem still existing?

**Comment by vr6syncro** [comment]
no problems but i am not sure if i fixed it or changed something

**Comment by BuZZy1337** [comment]
Please reopen if necessary.
