### ISSUE TITLE
[JsonConfig] Cannot read instance object: TypeError: Cannot read properties of undefined (reading 'enc')

### ISSUE THREAD

**Issue by Brainbug01** [iobroker-community-adapters/ioBroker.telegram#757]
Adapter Config öffnet sich nicht:

[JsonConfig] Cannot read instance object: TypeError: Cannot read properties of undefined (reading 'enc')

![image](https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/35106961/e077a64e-e293-43fa-8b0b-1f5668405291)

![image](https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/35106961/662a379b-654b-4172-b4d1-a53447122a1f)

![image](https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/35106961/a88e20ac-62c4-4ddc-a566-3cccd9e4566f)

Admin: 6.13.3
JS: 5.0.17
Telegram: 3.0.1

Bin mir aber nicht sicher ab es am admin update lag.

**Comment by Brainbug01** [comment]
6.13.5 behebt das Problem.

**Comment by mcm1957** [comment]
Thanks for feedback!
