### ISSUE TITLE
callback_data: Funktion aus InlineKeyboardMarkup auch im ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by Halloichbins1** [iobroker-community-adapters/ioBroker.telegram#801]
Es wäre schön wenn man auch im ReplyKeyboardMarkup eine callback_data: Funktion hätte, damit man in der Buttonbeschriftung mehr Freiheit hat.

--------------
It would be nice if you also had a callback_data: function in the ReplyKeyboardMarkup so that you have more freedom in button labeling.

BSP aus der Doku 

 ReplyKeyboardMarkup 
```js
sendTo('telegram.0', {
    text:   'Press button',
    reply_markup: {
        keyboard: [
            ['Line 1, Button 1', 'Line 1, Button 2'],
            ['Line 2, Button 3', 'Line 2, Button 4']
        ],
        resize_keyboard:   true,
        one_time_keyboard: true
    }
});
```

InlineKeyboardMarkup
```js
sendTo('telegram', {
    user: user,
    text: 'Click the button',
    reply_markup: {
        inline_keyboard: [
            [{ text: 'Button 1_1'**, callback_data: '1_1**_' }],
            [{ text: 'Button 1_2_'*, callback_data: '1_2_'** }]
        ]
    }
});
```

**Comment by kandkhm** [comment]
> Es wäre schön wenn man auch im ReplyKeyboardMarkup eine callback_data: Funktion hätte, damit man in der Buttonbeschriftung mehr Freiheit hat.
> 
> It would be nice if you also had a callback_data: function in the ReplyKeyboardMarkup so that you have more freedom in button labeling.
> 
> BSP aus der Doku
> 
> ReplyKeyboardMarkup sendTo('telegram.0', { text: 'Press button', reply_markup: { keyboard: [ ['Line 1, Button 1', 'Line 1, Button 2'], ['Line 2, Button 3', 'Line 2, Button 4'] ], resize_keyboard: true, one_time_keyboard: true } });
> 
> InlineKeyboardMarkup sendTo('telegram', { user: user, text: 'Click the button', reply_markup: { inline_keyboard: [ [{ text: 'Button 1_1'**, callback_data: '1_1**_' }], [{ text: 'Button 1_2_'*, callback_data: '1_2_'** }] ] } });

It's already working for me for a long time ...
At least in my scripts ... 
There is my, still not really published version of [telegram menu](https://github.com/PeterVoronov/ioBrokerTelegramMenuScript/tree/v0.9.5-dev)

**Comment by PeterVoronov** [comment]
> Es wäre schön wenn man auch im ReplyKeyboardMarkup eine callback_data: Funktion hätte, damit man in der Buttonbeschriftung mehr Freiheit hat.
> 
> It would be nice if you also had a callback_data: function in the ReplyKeyboardMarkup so that you have more freedom in button labeling.
> 
> BSP aus der Doku
> 
> ReplyKeyboardMarkup sendTo('telegram.0', { text: 'Press button', reply_markup: { keyboard: [ ['Line 1, Button 1', 'Line 1, Button 2'], ['Line 2, Button 3', 'Line 2, Button 4'] ], resize_keyboard: true, one_time_keyboard: true } });
> 
> InlineKeyboardMarkup sendTo('telegram', { user: user, text: 'Click the button', reply_markup: { inline_keyboard: [ [{ text: 'Button 1_1'**, callback_data: '1_1**_' }], [{ text: 'Button 1_2_'*, callback_data: '1_2_'** }] ] } });

For me it's working, if I make id via JavaScript? Or did you speak about blockly?
