### ISSUE TITLE
Errors on deleteMessage thrown when user is not set

### ISSUE THREAD

**Issue by paluki** [iobroker-community-adapters/ioBroker.telegram#810]
**Describe the bug**  
When deleteMessage is called and the "user" attribute is not set there is an error thrown for every authenticated user and a success for the one specified in chat_id. 
"Failed sending [chatId - xxxxxxxxxx]: Error: ETELEGRAM: 400 Bad Request: message to delete not found"
Where chatId which is shown in the error is always the Id of the last authenticated user.

This is especially bad when you're deleting messages from groups because the user attribute doesn't accept groupIds and i did not find an alternative in the documentation. 

**To Reproduce**  
Call deleteMessage with a valid chat_id and message_id but with no user set. / Set user to a groupId or name

**Expected behavior**  
No errors thrown on empty user or a way to set user or another attribute to a groupId.

**Versions:**  
 - Adapter version: 3.1.0 + 3.2.1
 - JS-Controller version: 4.0.23 + 5.0.19
 - Node version: 18.20.1
 - Operating system: Raspbian 10 buster

**Comment by klein0r** [comment]
1. Edit Bot settings using Botfather
2. Choose "Channel Admin Rights"
3. Enable "Delete Messages"

<img width="495" alt="Screenshot 2024-06-19 at 21 25 41" src="https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/1959049/dcbe04ca-798b-4e7a-9f87-77685dd4b568">

**Comment by paluki** [comment]
@klein0r  
Sorry for the late reply, the problem is not that I am not able to delete messages which would be fixed by your suggestion.

The deleteMessage command gets send to every user in telegram.0.communicate.users if "user" is not set in the call, which naturally produces errors for every other user than the group, weirdly the error message always contains the id of the last user in the users json
But the message does get deleted.

I did figure out that if you specify the first_name of the bot as user everything works as expected
this should maybe get added to the documentation, as far as i understood it normally user should be the targeted conversation username
