### ISSUE TITLE
Error 25 during newest update from 3.1.0 to 3.2.1

### ISSUE THREAD

**Issue by ltspicer** [iobroker-community-adapters/ioBroker.telegram#812]
$ iobroker upgrade telegram@3.2.1 --debug

Update telegram from @3.1.0 to @3.2.1

host.raspberrypi Adapter "system.adapter.telegram.0" is stopped.

NPM version: 10.5.0

Installing iobroker.telegram@3.2.1... (System call)

npm ERR! code ENOTEMPTY

npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/axios' -> '/opt/iobroker/node_modules/.axios-5PaJDuuS'npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-04-20T07_24_55_936Z-debug-0.log

Try to solve ENOTEMPTY error automatically

host.raspberrypi deleted npm temp directory: ".axios-5PaJDuuS")

host.raspberrypi deleted npm temp directory: ".follow-redirects-vRGWWNjd")

host.raspberrypi deleted npm temp directory: ".iobroker.zigbee-1JQaSLfT")

host.raspberrypi deleted npm temp directory: ".semver-n8m5lQuN")

host.raspberrypi deleted npm temp directory: ".tar-stream-ptmKYjN0")

host.raspberrypi deleted npm temp directory: ".zigbee-herdsman-KZGHBvfL")

host.raspberrypi deleted npm temp directory: ".zigbee-herdsman-converters-DzgWyYTV")

Installing iobroker.telegram@3.2.1... (System call)

npm ERR! code ENOTEMPTYnpm ERR! syscall renamenpm ERR! path /opt/iobroker/node_modules/@leichtgewicht/ip-codec

npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/@leichtgewicht/ip-codec' -> '/opt/iobroker/node_modules/@leichtgewicht/.ip-codec-YgBQavZW'

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-04-20T07_25_24_805Z-debug-0.log

npm ERR! code ENOTEMPTYnpm ERR! syscall renamenpm ERR! path /opt/iobroker/node_modules/@leichtgewicht/ip-codecnpm ERR! dest /opt/iobroker/node_modules/@leichtgewicht/.ip-codec-YgBQavZWnpm ERR! errno -39npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/@leichtgewicht/ip-codec' -> '/opt/iobroker/node_modules/@leichtgewicht/.ip-codec-YgBQavZW'npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-04-20T07_25_24_805Z-debug-0.loghost.raspberrypi Cannot install iobroker.telegram@3.2.1: 217

ERROR: Process exited with code 25

**Comment by Apollon77** [comment]
Please execute „iob fix“ and try again

**Comment by mcm1957** [comment]
Please execute

```
iob stop
iob fix
iob start
```

**Comment by ltspicer** [comment]
Danke euch, das hat's gebracht ^^
