### ISSUE TITLE
Nachricht wird nicht in Thema gesendet / Message is not sent in topic / theme / subgruoup

### ISSUE THREAD

**Issue by nhet** [iobroker-community-adapters/ioBroker.telegram#813]
Ich habe innerhalb von einer Gruppe ein neues Thema erstellt. Man könnte da vermutlich auch von Subgruppe sprechen. In der Telegram Web UI bekommmen diese "Gruppen" eindeutige IDs in Form einer '_X' an die eigentliche ChatID angefügt. Wobei X für die jeweilige Gruppe steht.
Wenn ich nun mit diesen neuen ChatIDs über den Adapter neue Nachrichten sende, landen diese alle im Hauptchat, ich möchte aber, dass die Nachrichten in die entsprechenden Subgruppen gelangen.

I have created a new topic within a group. You could probably also call it a subgroup. In the Telegram Web UI, these ‘groups’ get unique IDs in the form of an '_X' appended to the main ChatID. Where X stands for the respective group.
If I now send new messages with these new ChatIDs via the adapter, they all end up in the main chat, but I want the messages to end up in the corresponding subgroups.

**Comment by mcm1957** [comment]
https://forum.iobroker.net/topic/74411/telegram-adapter-sendet-nicht-in-subgruppen

**Comment by nhet** [comment]
https://medium.com/@rezvovvad/send-notifications-to-a-specific-topic-in-the-telegram-chat-1f570b7ab929

**Comment by klein0r** [comment]
@nhet Looks like you have to specify the correct chat_id for the subgroup (with an underscore):

```
"chat_id": "-1001234567890_1234"
```

**Comment by nhet** [comment]
In addition to the complete chat_id, it is also necessary to enter the message_thread_id. The message_thread_id only contains the value after the underscore of the chat_id.
The message_thread_id element is probably not yet in the current Telegram Bot implementation.

**Comment by klein0r** [comment]
Please test version 3.7.0

Use state `communicate.requestResponse` to respond to the last chat id (and thread id). Or send a message directly to a thread in a supergroup:

Example:

https://github.com/iobroker-community-adapters/ioBroker.telegram/blob/ac860092866628cc10b42680c4d08a269c4d11f8/docs/en/README.md?plain=1#L258-L267

**Comment by Flyor** [comment]
@klein0r Gibt es hier die Möglichkeit auch über das sendTo Blockly die Thread ID zu setzen?

**Comment by klein0r** [comment]
@Flyor Nur mit dem generischen sendTo-Block. Aber dann ja

**Comment by Flyor** [comment]
> [@Flyor](https://github.com/Flyor) Nur mit dem generischen sendTo-Block. Aber dann ja
@klein0r 

Danke für die Rückmeldung, hast du ein Beispiel wie das dann aussehen soll? Ich habe jetzt etwas rumexperimentiert, er schreibt aber  immer:

Failed sending [chatId - 588*****]: Error: ETELEGRAM: 400 Bad Request: message text is empty


![Image](https://github.com/user-attachments/assets/66976e4d-12c9-4a68-8ef9-a313a0355196)

**Comment by Flyor** [comment]
Zur Info:

Hab es selbst rausbekommen, wenn man den normalen Telegram sendto Block nimmt und beim Empfänger hinterdie Chat ID 1234 noch mit _ die Chat ID dahinter setzt (beispielsweise 1234_6) kommt es im richtigen Topic an. Trotzdem Danke!

**Comment by Flyor** [comment]
Ich dachte ich hätte es geschafft, aber leider bleibt nur der Weg über die Einbettung eines JS Skripts. Denn wenn ich den sendto block in JS konvertiere, kommt da vieles dazu was scheinbar stört. Erst wenn ich das händisch alles raus lösche, funktioniert es. Kannst du mir ein Beispiel Blockly zeigen, wie es aufgebaut sein muss damit es funktioniert, @klein0r ? danke für Deine Unterstützung.

**Comment by mcm1957** [comment]
Das Issue ist seit juli 2024 geschlossen.
Bitte bei Problemen ein neues Issue mit den entsprchenden Informationen aufmachen. Allgemeine Fragen zu erVerwendung das Adapetrs bitte im Forum (https://forum.ioborker.net) stellen.
