### ISSUE TITLE
[JS-CONTROLLER 6] LE code must be removed / migrated

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.telegram#819]
To work with js-controlelr 6 reference to `utils.commonTools.letsEncrypt` must be removed and code needs to be adapted.

@foxriver76 
@klein0r 
@Apollon77 

Whoever feels fit enough to know what to do exactly.

**Comment by foxriver76** [comment]
migration already done but cannot build/publish because the latest version of `@iobroker/json-config` has issues

**Comment by mcm1957** [comment]
fixed with 3.3.0
