### ISSUE TITLE
[JsonConfig] Cannot set object: TypeError: Cannot read properties of undefined (reading 'lib')

### ISSUE THREAD

**Issue by telly81** [iobroker-community-adapters/ioBroker.telegram#829]
Hallo, ich habe seit der Neuinstallation des Telegram Adapters probleme diesen einzurichten. 

Wenn ich Ihn Konfiguriere kommt immer die Meldung : [JsonConfig] Cannot set object: TypeError: Cannot read properties of undefined (reading 'lib') und die Werte werden nicht übernommen. Woher kommt die Meldung und was fehlt Ihm denn?

Danke für die Hilfe

**Comment by mcm1957** [comment]
Please add release version information to every problem reported:
- version of adapter:
- version of js-controller:
- version of admin:
- nodeJS version installed:
- Operating system type / version:

**Comment by telly81** [comment]
Adpter version v3.1.0 - bis zur aktuellen

O
Plattform: linux
Betriebssystem: linux
Architektur: arm64
CPUs: 4
Geschwindigkeit: 1800 MHz
Modell: Cortex-A72
RAM: 7.6 GB
System-Betriebszeit: 00:04:25
Node.js: v18.19.1
time: 1717575242190
timeOffset: -120
NPM: 10.2.4
Adapter-Anzahl: 537
Datenträgergröße: 117.0 GB
Freier Festplattenspeicher: 94.2 GB
Aktive Instanzen: 32
Pfad: /opt/iobroker/
Betriebszeit: 00:33:49

telegram.5 | PID | Zeit | debug | Nachricht
-- | -- | -- | -- | --
telegram.5 | 3210 | 2024-06-05 10:05:41.191 | error | Token is not set!
telegram.5 | 3210 | 2024-06-05 10:05:41.022 | info | starting. Version 3.1.0 in /opt/iobroker/node_modules/iobroker.telegram, node: v18.19.1, js-controller: 5.0.19
telegram.5 | 3210 | 2024-06-05 10:05:40.549 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
telegram.5 | 3015 | 2024-06-05 10:05:34.623 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
telegram.5 | 3015 | 2024-06-05 10:05:34.619 | info | terminating
telegram.5 | 3015 | 2024-06-05 10:05:34.113 | info | Got terminate signal TERMINATE_YOURSELF

**Comment by mcm1957** [comment]
Why did you vlose this issue

**Comment by telly81** [comment]
After I had updated the system for the third time, the adapter ran again without errors

**Comment by mcm1957** [comment]
Thanks for info
