### ISSUE TITLE
No update possible due to missing button 

### ISSUE THREAD

**Issue by FlexerJR** [iobroker-community-adapters/ioBroker.telegram#832]
![image](https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/40354380/859ed590-a361-413d-bf17-1bd68bfb98c6)

Hello Devs, today i noticed that there is no button to upgrade the adapter. I'm not sure if this is a problem of iob or the adapter.

Best regards. 

Plattform:
linux
Betriebssystem:
linux
Architektur:
x64
CPUs:
4
Geschwindigkeit:
3295 MHz
Modell:
Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
RAM:
15.4 GB
System-Betriebszeit:
00:13:32
Node.js:
v18.17.1
time:
1718267911911
NPM:
9.6.7
Adapter-Anzahl:
624
Datenträgergröße:
58.8 GB
Freier Festplattenspeicher:
16.7 GB
Aktive Instanzen:
55
Pfad:
/opt/iobroker/
Betriebszeit:
00:04:23
aktiv:
_nodeCurrent:
18.17.1
_nodeNewest:
18.20.3
_nodeNewestNext:
18.20.3
_npmCurrent:
9.6.7
_npmNewest:
9.6.7
_npmNewestNext:
10.7.0

**Comment by mcm1957** [comment]
You do not note the admin version in use. Most likely you use adminn7. This is a know Bug at admin 7.0.1. Please see admin issues  Admin 7.x.x. has been revoked..

Please downgrade to latest admin Version  (6.x.x).  This shizld solve the problem.

**Comment by FlexerJR** [comment]
Oh ok thank you very much. Now it works. Wasn't aware of this bug. 

👍🏻
