### ISSUE TITLE
Blockly für "frage per Telegram" fehlerhaft

### ISSUE THREAD

**Issue by Eistee82** [iobroker-community-adapters/ioBroker.telegram#833]
**Describe the bug**  
Beim "fragen per Telegram" Blockly Block wird der Empfänger Benutzername immer in blass angebunden. Wenn ich jetzt nur per Chat-ID die Frage stellen möchte kommt der fehler das er den User nicht kennt. beim normalen telegram Block wird der Empfänger Benutzername nicht fest vorgegeben so das hier die Verwendung nur mit Chat-ID funktioniert.
Ich vermute der Fehler liegt hier: https://github.com/iobroker-community-adapters/ioBroker.telegram/blob/master/admin/blockly.js#L385-L389
kenne mich aber damit nicht genug aus.

**Screenshots & Logfiles**  
![image](https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/1881217/83dd2e2e-b3ff-432f-8727-65fb2c06798a)

**Versions:**  
 - Adapter version: v3.6.0
 - JS-Controller version: 6.0.5
 - Node version: v20.14.0
 - Operating system: debian

**Comment by mcm1957** [comment]
@Eistee82 
telegram 8.6.0 existiert nicht. Das dürfte die Version des javascript Adapters sein.

Bitte die Telegramm Version ergänzen und auch mit der aktuellsetn Telegramm Version mal testen.

**Comment by Eistee82** [comment]
> @Eistee82 telegram 8.6.0 existiert nicht. Das dürfte die Version des javascript Adapters sein.
Korrigiert. v3.6.0 meine ich

**Comment by klein0r** [comment]
@Eistee82 Das nächste Mal gerne ein PR erstellen 👍
