### ISSUE TITLE
Telegram instance loses token

### ISSUE THREAD

**Issue by marian-t-web-de** [iobroker-community-adapters/ioBroker.telegram#834]
**Describe the bug**  
since ver.3.3.2 Telegram instance loses token

**To Reproduce**  
1. Go to instance overview
2. See Instance "telegram" status
3. "telegram" status is every day/by restart warning
4. See log error "2024-06-24 05:59:59.024  - [31merror[39m: telegram.0 (2151) Token is not set!"

**Expected behavior**  
Telegram instance token stays unchanged as set manually

**Screenshots & Logfiles**  
log error "2024-06-24 05:59:59.024  - [31merror[39m: telegram.0 (2151) Token is not set!"

**Versions:**  
 - Adapter version: 3.3.2
 - Plattform: docker (official image - v9.0.1)
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1800 MHz
Modell: ARMv7 Processor rev 3 (v7l)
RAM: 3.7 GB
System-Betriebszeit: 91 T. 12:01:56
Node.js: v18.19.0
time: 1719212589646
timeOffset: -120
NPM: 10.2.3
Adapter-Anzahl: 539
Datenträgergröße: 27.9 GB
Freier Festplattenspeicher: 3.1 GB
Aktive Instanzen: 20
Pfad: /opt/iobroker/
Betriebszeit: 24 T. 12:58:53
aktiv:

**Additional context**

**Comment by mcm1957** [comment]
Current telegram release is 3.6.0.
Please check whether this problem still exists with current version of adapter.

In addtion please add missing version information

adapter: 3.3.2 -> to be testets with 3.6.0
js-controller:
admin:
node: 18.19.0

**Comment by marian-t-web-de** [comment]
Stable version of the telegram adapter in github is still 3.3.2. therefore i think it is the reason 3.6.0 is  not available in iobroker yet.
Make it pls. to stable first.
Your question "In addtion please add missing version Information", You mean version of what?

**Comment by marian-t-web-de** [comment]
Sorry i see it now first:
js-controller: 5.0.19
admin: 6.13.16

**Comment by mcm1957** [comment]
3.6.0 is available at latest repository.
Please Test with this Version.

**Comment by marian-t-web-de** [comment]
3.6.0 is not available in iobroker yet:
![Screenshot_20240625_204054_Chrome](https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/37208979/72dd1c05-1b56-495d-ac42-f75d881c3932)

**Comment by mcm1957** [comment]
3.6.0 is available at LATEST repository.

- Switch to latest / beta repository
- press search for updates
- update to current lates version (which is 3.6.0)
- switch back to stable repository

![image](https://github.com/iobroker-community-adapters/ioBroker.telegram/assets/28575778/ea2959a1-b22a-4f61-bf84-6855c5db1d62)

**Comment by marian-t-web-de** [comment]
3.6.0 is loses Token also, no changes

**Comment by Apollon77** [comment]
Please check the ioBroker log for any issues like DB not able to write files or such. because this should never happen and means that your configuration gets not stored.
Is this only happening when restarting adapter? Or is whole js.controller restarted?

Please enable expert mode in admin, then go Objects -> system.adapter.telegram.0 and use the pencil icon on right to see the instance config. When you see the error copy the json. check for "common.token".
Then enter the token in admin panel and save, adapter should restart.
check the json again- token now in?
restart telegram?  working? if not check object again
restart js-controller - check json again

**Comment by marian-t-web-de** [comment]
Under system.adapter.telegram.0 is token available (encrypted), but not "commn.token"(?):

`"native": {
    "server": "false",
    "port": "8443",.
     ...
    "answerTimeoutSec": 60,
    "token": "$/aes-192-cbc:fe3f6ae85b46735e8c158e4a5a183580:1b9ee6dab9d4b6c5506a880462d10a6b11aa58071d0dbb2ea4cababbecfc06b39e4d079037dfdf5a0bad81d95b1eee10"
  },`

The token is in the instance settings on the morning after router-restart in the night empty again (iob will be not restartet).
Log:
`2024-06-26 05:59:40.935  - [32minfo[39m: host.iobroker instance system.adapter.telegram.0 started with pid 26444
2024-06-26 05:59:42.506  - [32minfo[39m: hm-rpc.0 (26405) starting. Version 1.17.0 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v18.19.0, js-controller: 5.0.19
2024-06-26 05:59:43.050  - [32minfo[39m: hm-rpc.0 (26405) xmlrpc server is trying to listen on 192.168.178.30:2001
2024-06-26 05:59:43.056  - [32minfo[39m: hm-rpc.0 (26405) xmlrpc client is trying to connect to 192.168.178.208:2001/ with ["http://192.168.178.30:2001","iobroker:hm-rpc.0:f450d720733ca0e751df7aaee8207549"]
2024-06-26 05:59:43.186  - [32minfo[39m: hm-rpc.0 (26405) xmlrpc <- system.listMethods ["iobroker:hm-rpc.0:f450d720733ca0e751df7aaee8207549"]
2024-06-26 05:59:43.204  - [32minfo[39m: hm-rpc.0 (26405) xmlrpc <- listDevices ["iobroker:hm-rpc.0:f450d720733ca0e751df7aaee8207549"]
2024-06-26 05:59:43.327  - [32minfo[39m: hm-rpc.0 (26405) xmlrpc -> 52 devices
2024-06-26 05:59:43.359  - [32minfo[39m: hm-rpc.0 (26405) Connected
2024-06-26 05:59:47.245  - [32minfo[39m: alexa2.0 (26429) starting. Version 3.26.5 in /opt/iobroker/node_modules/iobroker.alexa2, node: v18.19.0, js-controller: 5.0.19
2024-06-26 05:59:47.326  - [32minfo[39m: alexa2.0 (26429) Starting Alexa2 adapter ... it can take several minutes to initialize all data. Please be patient! A done message is logged.
2024-06-26 05:59:48.398  - [32minfo[39m: telegram.0 (26444) starting. Version 3.6.0 in /opt/iobroker/node_modules/iobroker.telegram, node: v18.19.0, js-controller: 5.0.19
2024-06-26 05:59:48.565  - [31merror[39m: telegram.0 (26444) Token is not set!`

For me is not clear where I can see the error copy the json - in log is nothing about.

By the way: iobroker ist a docker container (see my first post above) - but other adapter keeps their settings.

**Comment by mcm1957** [comment]
Ok. instance parameters are store at local. So this is OK.
Does this entry exist when the problem occures too or is it removed / changed?

And if I read this correctly:
- restarting the telegram instance works and there is no message about an unset token
- the complete ioBroker instance is not restarted

So what restart do you refer to when you wite: '"telegram" status is every day/by restart warning' ?
Guess you refer to a restart of your router. Please confirm.
Is the token entry at the instance object empty or unchanged after the router restart?

**Comment by marian-t-web-de** [comment]
I referred to a restart of my router. The token entry at the instance object empty at the morning after router and telegram restart.
I've checked without telegram restart in the night is everything ok - so was last night.
I'll check the logs of few next days and reopen the issue if wrong again.

**Comment by klein0r** [comment]
@marian-t-web-de The token is a protected attribute.

Do you start/stop/restart the instance automatically by using `setObject`?

**Comment by marian-t-web-de** [comment]
Yes, I've forgotten to replace it with extendObject() at one place.
This issue can therefore be closed, thanks for Your help.
