### ISSUE TITLE
Blockly: Enable multiple Telegram message receivers

### ISSUE THREAD

**Issue by Hausmeister486** [iobroker-community-adapters/ioBroker.telegram#835]
For alarm messages that are to be sent to several Telegram recipients at the same time, it would be helpful to be able to specify several recipients (comma separated) instead of having to implement the logic separately for each recipient.

Best regards,

**Comment by mcm1957** [comment]
implemented at 3.8.1

**Comment by Hausmeister486** [comment]
It worked very well during an initial test
