### ISSUE TITLE
adapter stopped working

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.telegram#877]
Hi all, I just noticed that my telegram adapter has stopped working. I have a bot that was used successfully for quite a long time but not anymore. I am not aware of any change that might have caused this. Could anyone point me into a direction how to trouble-shoot this?

BR

**Comment by daniel-lo** [comment]
Admin 7.1.5
Nodejs: v20.18.0
js-controller: 6.0.11
Telegram Adapter: 3.9.0
Instance-Status: green (all green)

used rsesponse to send a message ...
no log (debug)

**Comment by daniel-lo** [comment]
@mcm1957
I'd classify this as bug .. but not sure .. information added above.

**Comment by mcm1957** [comment]
**I still recommend to discuss this issue at the forum** - you will get responses from more users there.
The above log is most likely no DEBUG log. There is no indication that you wrote anything to any state logged.
Please set instance to debug level and reproduce the problem.

How do you write data to responce state? Is ack set to false?

**Comment by daniel-lo** [comment]
You were correct "debug" didn't stick .. but typing something via "response" still doesn't trigger anything. I already tried renewing all the objects.

<html><body>

telegram.0 | 2024-11-05 07:23:33.820 | debug | getMe:   {"id":765455045,"is_bot":true,"first_name":"ringbot","username":"ring53bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false}
-- | -- | -- | --
telegram.0 | 2024-11-05 07:23:33.596 | debug | Start polling with: 300(number) ms interval
telegram.0 | 2024-11-05 07:23:33.390 | info | starting. Version 3.9.0 in /opt/iobroker/node_modules/iobroker.telegram, node: v20.18.0, js-controller: 6.0.11
telegram.0 | 2024-11-05 07:23:32.963 | debug | Plugin sentry Initialize Plugin (enabled=true)
telegram.0 | 2024-11-05 07:23:32.928 | debug | States connected to redis: 127.0.0.1:9000
telegram.0 | 2024-11-05 07:23:32.869 | debug | States create User PubSub Client
telegram.0 | 2024-11-05 07:23:32.868 | debug | States create System PubSub Client
telegram.0 | 2024-11-05 07:23:32.857 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
telegram.0 | 2024-11-05 07:23:32.833 | debug | Objects connected to redis: 127.0.0.1:9001
telegram.0 | 2024-11-05 07:23:32.826 | debug | Objects client initialize lua scripts
telegram.0 | 2024-11-05 07:23:32.788 | debug | Objects create User PubSub Client
telegram.0 | 2024-11-05 07:23:32.787 | debug | Objects create System PubSub Client
telegram.0 | 2024-11-05 07:23:32.785 | debug | Objects client ready ... initialize now
telegram.0 | 2024-11-05 07:23:32.755 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
telegram.0 | 2024-11-05 07:23:27.076 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
telegram.0 | 2024-11-05 07:23:27.074 | info | terminating
telegram.0 | 2024-11-05 07:23:26.572 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>

**Comment by daniel-lo** [comment]
As I mentioned .. I didn't change anything .. these settings worked. And I know the bot works because my n8n instance provides me with messages.

![grafik](https://github.com/user-attachments/assets/294a1c3f-ba78-4a47-abbf-a1d7b8f2cb43)
![grafik](https://github.com/user-attachments/assets/005ddfac-4466-44d3-8863-db0691e3ea6b)

**Comment by daniel-lo** [comment]
Diag shows adapter inactive .. in the GUI it's green. "iob start telegram" show no output.

**Comment by daniel-lo** [comment]
@mcm1957 

I removed the adapter and reinstalled it.
I made a new bot and used the new token.
I made a blockly that sends a test message every minute.

Nothing!


<html><body>
<div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T4"><a type="box" href="http://192.168.178.115:8081/#tab-instances" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T4"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T6"><a type="box" href="http://192.168.178.115:8081/#tab-objects" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T6"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T8"><a type="box" href="http://192.168.178.115:8081/#tab-enums" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T8"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T10"><a type="box" href="http://192.168.178.115:8081/#tab-logs" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T10"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T12"><a type="box" href="http://192.168.178.115:8081/#tab-users" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T12"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T14"><a type="box" href="http://192.168.178.115:8081/#tab-hosts" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T14"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T16"><a type="box" href="http://192.168.178.115:8081/#tab-files" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T16"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T18"><a type="box" href="http://192.168.178.115:8081/#tab-backitup-0" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T18"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T20"><a type="box" href="http://192.168.178.115:8081/#tab-javascript" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T20"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T22"><a type="box" href="http://192.168.178.115:8081/#tab-node-red-0" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T22"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T24"><a type="box" href="http://192.168.178.115:8081/#tab-scenes" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T24"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T26"><a type="box" href="http://192.168.178.115:8081/#tab-devices" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T26"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T28"><a type="box" href="http://192.168.178.115:8081/#tab-text2command-0" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T28"><div style="display: flex; align-items: center;"></div></a></div><div style="cursor: move; opacity: 1;" draggable="true" data-handler-id="T30"><a type="box" href="http://192.168.178.115:8081/#tab-zigbee-0" style="cursor: move; opacity: 1; color: inherit; text-decoration: none;" data-handler-id="T30"><div style="display: flex; align-items: center;"></div></a></div><div style="position: sticky; bottom: 0px; right: 0px; width: fit-content; margin-left: auto; margin-top: auto; transition: opacity 0.5s; opacity: 0;"></div><div class="MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-xnuxc9" style="--Paper-shadow: 0px 2px 1px -1px rgba(0,0,0,0.2),0px 1px 1px 0px rgba(0,0,0,0.14),0px 1px 3px 0px rgba(0,0,0,0.12); width: 100%; height: 100%; overflow: hidden;" elevation1="[object Object]" elevation2="[object Object]" elevation3="[object Object]" elevation4="[object Object]" elevation5="[object Object]" elevation6="[object Object]" elevation7="[object Object]" elevation8="[object Object]" elevation9="[object Object]" elevation10="[object Object]" elevation11="[object Object]" elevation12="[object Object]" elevation13="[object Object]" elevation14="[object Object]" elevation15="[object Object]" elevation16="[object Object]" elevation17="[object Object]" elevation18="[object Object]" elevation19="[object Object]" elevation20="[object Object]" elevation21="[object Object]" elevation22="[object Object]" elevation23="[object Object]" elevation24="[object Object]"><div class="MuiGrid2-root MuiGrid2-container MuiGrid2-wrap-xs-nowrap MuiGrid2-direction-xs-column css-fzgu8j"><div class="MuiGrid2-root MuiGrid2-container MuiGrid2-direction-xs-row css-1af9k7t"></div></div></div><span aria-label="Fehler anzeigen" class="MuiBadge-root css-tf5ugs"><span class="MuiBadge-badge MuiBadge-standard MuiBadge-invisible MuiBadge-anchorOriginTopRight MuiBadge-anchorOriginTopRightRectangular MuiBadge-overlapRectangular MuiBadge-colorError css-c6vaoj">0</span></span><span aria-label="Fehler und Warnungen anzeigen" class="MuiBadge-root css-1mss9xc"></span><span aria-label="Fehler und Warnungen anzeigen" class="MuiBadge-root css-1mss9xc"><span class="MuiBadge-badge MuiBadge-standard MuiBadge-anchorOriginTopRight MuiBadge-anchorOriginTopRightRectangular MuiBadge-overlapRectangular css-h6q8c4">2</span></span><div style="flex-grow: 1;"></div><div class="MuiGrid2-root MuiGrid2-container MuiGrid2-direction-xs-row css-1af9k7t"><div style="flex-grow: 1;"></div><p class="MuiTypography-root MuiTypography-body2 css-a9oeij" title="Geschätzte Größe" style="margin-right: 1rem; margin-left: 1rem;">Log-Größe: <span style="font-style: italic;">2.1 MB</span></p></div><div class="MuiGrid2-root MuiGrid2-direction-xs-row css-77c867"><div class="MuiTableContainer-root css-kge0eu" style="height: 100%;">
 
--



</body>
</html>

**Comment by daniel-lo** [comment]
Ich bekomme aber auch keine bot started/stopped meldungen vom Bot.

**Comment by mcm1957** [comment]
Thanks for feedback.
