### ISSUE TITLE
neustart des adapters auch bei abbruch

### ISSUE THREAD

**Issue by nob0dy80** [iobroker-community-adapters/ioBroker.telegram#96]
Der Adapter startet neu, obwohl man in der Konfiguration auf abbrechen gedrückt hat.

Adapter restarts, even you chose cancle in configuration.

**Comment by BuZZy1337** [comment]
Kann ich nicht bestätigen..

Wie genau gehst du vor?
Ich ändere irgend eine Einstellung, klicke dann Abbrechen - bestätige mit OK und der Adapter wird NICHT neu gestartet..?

![image](https://user-images.githubusercontent.com/6979405/53940481-19a54d80-40b6-11e9-8590-250ab75f9f7c.png)

**Comment by nob0dy80** [comment]
@BuZZy1337 
Frag mich nicht was ich da gesehen habe gestern. 
Glaube habe es vermutlich mit einem anderen adapter verwechselt.
Bitte schliessen.
