### ISSUE TITLE
ChannelID/GroupID dont work at the moment?

### ISSUE THREAD

**Issue by Gatlingod** [iobroker-community-adapters/ioBroker.telegram#97]
Hi,

ChannelID and GroupID sending dont work at the moment?

For more information please see:
https://github.com/shurillu/CTBot/issues/18

Gruß

**Comment by BuZZy1337** [comment]
Ist das eine Frage? Oder eine Feststellung? :laughing:
Bei mir gehen GruppenChats ohne Probleme.. Channels verwende ich persönlich nicht. 

Gruß

**Comment by Gatlingod** [comment]
Stimmt klappt 1a mit Gruppe und Channel, ich hatte ein anderes Problem.
Dann kann man das hier wohl closen.
