### ISSUE TITLE
*request* Gruppen Funktion

### ISSUE THREAD

**Issue by eXplOiD1** [iobroker-community-adapters/ioBroker.telegram#99]
Guten Tag,
es ist ja bereits möglich Nachrichten in eine Gruppe zu senden, wird es auch irgendwann möglich sein Befehle über einen Gruppen Chat an den bot zu geben ?

mfg
eXplOiD

**Comment by BuZZy1337** [comment]
Wie meinst du das?
Der Adapter kann mit einer Gruppe genau so interagieren wie mit einem "Einzelchat".. 

Hast du ein Beispiel was bei dir nicht funktioniert oder was du damit meinst? 

Gruß

**Comment by eXplOiD1** [comment]
oh ok ich weiß wo mein Fehler lag es war der falsche Syntax kann geschlossen werden
